### ISSUE TITLE
Show separate tabs for different Windows of same program 

### ISSUE THREAD

**Issue by raeesiqbal** [linuxdeepin/dde-dock#1]
In the classic mode, there should be an option to enable Microsoft Windows like behavior in taskbar to enable visibility of all windows of the same program rather than just one. It will enable faster switching and make it easier to drop things to the right window.
I have two Google Chrome windows open In this screenshot but I can see only one. I'll have to hover the taskbar to go to the other window while there is a lot of room to show the other window in the taskbar.
![deepinscreenshot20160211205315](https://cloud.githubusercontent.com/assets/10067728/12981228/a983fafc-d0d7-11e5-97a9-f968cdf1ad22.png)

**Comment by raeesiqbal** [comment]
Any updates on this?

ref: https://bugzilla.deepin.io/show_bug.cgi?id=4910

**Comment by manateelazycat** [comment]
We will remove classic mode from new version dock along with deepin 15.3.

In new version of dock just provide win7 mode and mac mode, of course new version of dock will provide a feature that allowed user customize size of dock

**Comment by raeesiqbal** [comment]
Will I be able to see two Chrome tabs in the Dock Win7 mode when I have two windows of Chrome open?
