### ISSUE TITLE
deepin-tool-kit 怎么安装？

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/dde-dock#10]
dockconstants.h, dockplugininterface.h , dockpluginproxyinterface.h ,  dcalendar.h 文件找不到。
时间日期那个插件太复杂，我需要一个在任务栏显示文字的简单例子，然后我就可以写入其他信息了。

**Comment by sbwtw** [comment]
前 3 个应该是在 dde-dock-dev

**Comment by Match-Yang** [comment]
@sonichy DTK在此：https://github.com/linuxdeepin/deepin-tool-kit
这个例子是比较简单的：https://github.com/linuxdeepin/dde-dock/tree/master/dde-dock-shutdown-plugin
把图标换成一个带文字的Label就好了
