### ISSUE TITLE
Battery indicator not visible with dark theme

### ISSUE THREAD

**Issue by ibrokemypie** [linuxdeepin/dde-dock#100]
On darker themes, the battery indicator is still dark rather than light, unlike other icons, making it impossible to view.
![image](https://user-images.githubusercontent.com/7827846/41758119-dbdcb9c2-7629-11e8-9005-7c9b6da2ca55.png)

**Comment by jouyouyun** [comment]
@kirigayakazushin

**Comment by kirigayakazushin** [comment]
Dock will give priority to icons from the theme. We don’t know if the current theme looks appropriate.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
