### ISSUE TITLE
Network Plugin not disconnecting the wifi when disabled !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/dde-dock#102]
Hi,

As you can see the wifi is connected but disabling the wifi is not disconnecting the network ... the icon on the dock shows as connected even though the wireless switch is in a disabled state.

`ifconfig` shows the wifi is connected !!!

![wifi plugin enabled](https://user-images.githubusercontent.com/3283676/41809703-ab82661e-770f-11e8-9618-0e9d11a546d5.png)

![wifi dock plugin disabled](https://user-images.githubusercontent.com/3283676/41809705-ae52dcf2-770f-11e8-8c34-b5d4ea10bf77.png)

seems like a bug that is not disconnecting the wifi connection ...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
