### ISSUE TITLE
Feature Request ... Blur and Transparency control slider ?

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/dde-dock#104]
Hi,

With DeepinOS rapidly evolving to a better and better operating system ... could we expect of an option where the user could decide on the level of blurring and transparency for the dock ?

the deepin dock currently operates on a fixed setting basis   ... It would be a great if the user could customize their deepin dock to various degrees of Blur and Transparencies to match their taste and preferences ?

thanks.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
