### ISSUE TITLE
Docked icons disappear after that app upgrades

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/dde-dock#105]
Sometimes, at least when I upgrade Chromium, its icon in the dock disappear.

**Comment by VaZark** [comment]
i agree with @es20490446e .This seems to be case for Firefox as well. It seems to happen when either the browser or the dock is updated

**Comment by mamyn0va** [comment]
This issue appears for every manually docked apps (atom, postman, firefox...).

**Comment by es20490446e** [comment]
Happens with any other app, including the Deepin File Manager.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
