### ISSUE TITLE
dde-dock hangs and no longer responds.

### ISSUE THREAD

**Issue by gomes2191** [linuxdeepin/dde-dock#106]
at the beginning the deepin the dde-dock hangs and does not respond anymore including all the applications everything locks on the slash this occurs as soon as the deepin starts only the dde-dock hangs applications that are started outside the dde-dock respond normally. Deepin 15.6

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
