### ISSUE TITLE
dde-dock and control center freezes

### ISSUE THREAD

**Issue by shutterPL** [linuxdeepin/dde-dock#107]
I have disabled `audio` in `com.deepin.dde.daemon.audio` to make Pulseeffects work with deepin, but now dde-dock and control center hangs after login for about 20 seconds. This is output from journalctl.
`Activating service name='com.deepin.daemon.Audio' requested by ':1.19' (uid=1000 pid=1030 comm="/usr/bin/dde-dock "`

Why deepin tries to activate this service when I really don't need it.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
