### ISSUE TITLE
My menu bar doesn't appear after 10 seconds after witch reboot the notebook.

### ISSUE THREAD

**Issue by tgmarinho** [linuxdeepin/dde-dock#108]
when my notebook reboots the bar appears, and after 5 seconds the menu does not work and then the bar ends up disappearing when I click on something.

**Comment by acrossoffwest** [comment]
I have same problem

**Comment by tabuz** [comment]
And I also have same problem but it doesn't reboot my laptop. Have you guys found any solution? @acrossoffwest  @tgmarinho

**Comment by acrossoffwest** [comment]
> And I also have same problem but it doesn't reboot my laptop. Have you guys found any solution? @acrossoffwest @tgmarinho

No.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
