### ISSUE TITLE
能通过apt-get安装DDE开发环境吗？

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/dde-dock#11]
同步github再编译太复杂，能通过apt-get安装DDE开发环境吗，第一步首先实现在任务栏显示文字。

**Comment by Match-Yang** [comment]
可以的，比如你要做控制中心的开发：sudo apt-get build-dep dde-control-center
这样就能把控制中心开发依赖的必要的包装上，当然了，根据发行版不一样可能还会少些东西，这个就要自己动手了
