### ISSUE TITLE
用wps后左右键都失效

### ISSUE THREAD

**Issue by goodforever** [linuxdeepin/dde-dock#110]
用wps后左右键都失效，关机都要用键盘。当最近发现deepin时很为国人高兴，于是上周推荐老婆卸载ubuntu16.04,装了deepin linux。结果不单上网慢，应用打开也很慢，用wps后左右键还失效。要我帮她装回ubuntu 16.04。请问应用打开为何会慢那么多？

**Comment by BLumia** [comment]
提供的信息不足以判断慢是什么导致的，看上去和 dde-dock 项目也没有关系。

现在的 deepin 在资源占用等方面也有更多的优化了，如果有兴趣尝试的话，可以再次安装最新版本尝试，如果依然有相关问题可以前往 [Developer-Center](https://github.com/linuxdeepin/developer-center/issues) 提问并附带可能相关的信息，谢谢。
