### ISSUE TITLE
SSD very slow after upgrade

### ISSUE THREAD

**Issue by adrianopatrick** [linuxdeepin/dde-dock#119]
After updating, my SSD drive got very slow, the file manager gets stuck every time I try to access some file or folder from the directory that sits on my SSD

$ sudo hdparm -t /dev/sda 

/dev/sda:
 Timing buffered disk reads:   2 MB in  4.44 seconds = 460.84 kB/sec

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
