### ISSUE TITLE
battery value multiplied by 2

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-dock#12]
Since recently on Manjaro we experince the battery entry in the dock displaying a value multiplied by 2 while at the same time in the control center the value is correct:

![](http://imgur.com/9Fc6K9Jl.png)

The battery dock icon shows red with a question mark when the value rises +100, sometimes then the icon disappears completely.

**Comment by fasheng** [comment]
As I know, it already solved in upstream.
https://github.com/linuxdeepin/developer-center/issues/110

**Comment by funilrys** [comment]
Not fixed in arch ... I still have the probel @fasheng

**Comment by oberon2007** [comment]
Solved for me with **deepin-dock 3.0.11** Thank you! @funilrys are you on arch testing?

**Comment by sbwtw** [comment]
fixed at v4.0.0 @funilrys

**Comment by funilrys** [comment]
now I'm in arch testing @oberon2007
