### ISSUE TITLE
[4.7.4/4.7.5] Latest version makes the whole system unresponsive

### ISSUE THREAD

**Issue by julianxhokaxhiu** [linuxdeepin/dde-dock#120]
Hi,

since I've updated the package on Arch, I noticed that my entire systems became sluggish and unresponsive. Most of the time for any App that I open, there is some kind of "timeout" during the icon registration process.

Also, the system tray is totally unreliable: for eg. on Telegram you can right click on the icon, open a menu, but then the "minimize to tray" entry is grayed out, while on 4.7.3.5 is working normally.
Opening Teamviewer takes a lot of time and the system tray icon can't even be clicked.

I think you changed something in the code between these two releases. I'll try to find the commit if possible, but I guess you may find out yourself the issue, as it's easily reproducible.

```sh
$ uname -a
Linux arch 4.18.16-zen1-1-zen #1 ZEN SMP PREEMPT Sat Oct 20 22:06:49 UTC 2018 x86_64 GNU/Linux

$ pacman -Qs telegram           
local/telegram-desktop 1.4.3-1
    Official Telegram Desktop client

$ pacman -Qs teamviewer
local/teamviewer 13.2.26559-9
    All-In-One Software for Remote Support and Online Meetings
```

Thank you in advance,
Julian

**Comment by flubbe** [comment]
I noticed a similar behavior for the system tray: Clicking/hovering on a system tray icon (in most cases) does not seem to have a visible effect. But if you move the dock e.g. from the bottom of the screen to the top, the tray popup menus open and tooltips show below the dock.

Also, if you set the dock to automatically hide and click on a tray icon, you can see the window pop up behind the dock, but extending downwards and below the bottom of the screen.

I'm also on Arch (4.18.16-arch1-1-ARCH) using deepin-dock 4.7.4-1.

**Comment by antechdesigns** [comment]
Arch (4.18.16-arch1-1-ARCH) using deepin-dock 4.7.4-1
I can confirm the deepin-dock is borked!!
clicking on launcher sometimes doesn't close the menu, right clicking on sys tray icons shows pop up on the left. deepin-dock position: bottom, efficient mode

**Comment by antechdesigns** [comment]
> Please try deepin-dock 4.7.4-2.

How?

**Comment by felixonmars** [comment]
Your mirror should have the new release soon :)

**Comment by antechdesigns** [comment]
Updated, Still the same issues for me using 4.7.4-2

**Comment by julianxhokaxhiu** [comment]
I can confirm it is still broken for me as well. Tested 4.7.4-2

**Comment by felixonmars** [comment]
@justforlxz Any ideas on this issue?

**Comment by justforlxz** [comment]
Please upload ~/.cache/deepin/dde-dock/dde-dock.log, I can't reproduce this problem.

**Comment by zhtengw** [comment]
I think, upgrading these two packages "deepin-desktop-base" and "deepin-desktop-schemas" to the latest version can solve this issue.

**Comment by julianxhokaxhiu** [comment]
I'll try to upload the log file later today. Thank you for the prompt feedback.

@felixonmars in case you bump the packages mentioned by @zhtengw please ping me here, so I can try with them updated too.

**Comment by felixonmars** [comment]
@julianxhokaxhiu Both packages are updated. Please try again!

**Comment by julianxhokaxhiu** [comment]
Packages updated, noticied basically the same issues:

-> Telegram: if I close the window to leave it only in the systray if I click on it, it doesn't do nothing. Previously it opened back Telegram
-> Teamviewer: when you open the application it still take like 15 seconds to open, then when you close the window and you have only the systray icon, you can't either click nor right click on it. I have to terminate the process through Deepin System Monitor.

Here it is the 
[dde-dock.log](https://github.com/linuxdeepin/dde-dock/files/2524857/dde-dock.log)

**Comment by felixonmars** [comment]
Hrm, it's strange since I can never reproduce the Telegram problem. I don't have Teamviewer installed so I cannot verify the other.

**Comment by julianxhokaxhiu** [comment]
@felixonmars for teamviewer, use this AUR package ( https://aur.archlinux.org/packages/teamviewer/ ). You don't need an account, just open the app once installed.

For telegram I'm using this one: https://www.archlinux.org/packages/community/x86_64/telegram-desktop/

**Comment by antechdesigns** [comment]
Just updated still the same for me:
[dde-dock.log](https://github.com/linuxdeepin/dde-dock/files/2525296/dde-dock.log)

**Comment by antechdesigns** [comment]
Replicate: Set Efficient mode, bottom, right click shut down, sound or network in system tray
![deepinscreenshot_20181030100022](https://user-images.githubusercontent.com/29888048/47710532-ded46a00-dc2a-11e8-9277-a0a9375aefe3.png)

Does not happen when set to top, left or right
@julianxhokaxhiu @felixonmars @justforlxz

**Comment by julianxhokaxhiu** [comment]
Nope, not on my side. Every location has the same behavior for me, and I'm using it in Efficient mode yes.

**Comment by gonesimera** [comment]
Most of the items seem to work when I move the dock to the top, The plugins are there, even though they not listed, but the whole dock is unreliable.

![dock](https://user-images.githubusercontent.com/33421632/47769262-fae81200-dce3-11e8-8202-c516e1437ac2.png)

**Comment by antechdesigns** [comment]
> Most of the items seem to work when I move the dock to the top, The plugins are there, even though they not listed, but the whole dock is unreliable.
> 
> ![dock](https://user-images.githubusercontent.com/33421632/47769262-fae81200-dce3-11e8-8202-c516e1437ac2.png)

I Just done a fresh install of Manjaro Deepin on a VM Updated and exactly the same issues as you and the ones i mentioned above.
@gonesimera If you set the dock to the bottom and right click the shutdown button, does the pop up show on the left?

Thanks Ant

**Comment by julianxhokaxhiu** [comment]
@antechdesigns @gonesimera I think we're crossing the issue here. Don't won't to break the hype here, but mine is totally unrelated to this. Let's stay in topic.

This is issue is only about the fact that it's unresponsive with ( at least for me ) Telegram and Teamviewer apps, which is related to the way the dock registers icons and actions in the systray.

Everything else please create another issue if you want to discuss it.

**Comment by antechdesigns** [comment]
@julianxhokaxhiu sorry man

**Comment by gonesimera** [comment]
@julianxhokaxhiu apologies

**Comment by julianxhokaxhiu** [comment]
Updated to 4.7.5-1, still the same issues. I'll provide the logs soon.

**Comment by julianxhokaxhiu** [comment]
@felixonmars @justforlxz @zhtengw any update on this? Is there any progress being made?
