### ISSUE TITLE
Failed to compile,‘WindowList’ does not name a type

### ISSUE THREAD

**Issue by windowsair** [linuxdeepin/dde-dock#121]
In file included from /tmp/dde-dock/frame/item/appitem.h:27,
                 from /tmp/dde-dock/frame/controller/dockitemcontroller.h:30,
                 from /tmp/dde-dock/frame/controller/dockitemcontroller.cpp:22:
/tmp/dde-dock/frame/item/components/previewcontainer.h:53:59: error: ‘WindowList’ does not name a type; did you mean ‘QWindowList’?

**Comment by felixonmars** [comment]
dde-qt-dbus-factory is needed for building dde-dock.

**Comment by windowsair** [comment]
oh...It can work
