### ISSUE TITLE
Secondary menu not properly dhowing when dock is at bottom

### ISSUE THREAD

**Issue by buoyancy99** [linuxdeepin/dde-dock#122]
When clicking on wifi or volume, the dock tried to show secondary menu below the dock. But when the dock is at bottom, user cannot see them. 

![unnamed_1](https://user-images.githubusercontent.com/16475227/47626167-03272e00-dae7-11e8-9575-962c70023a34.png)

**Comment by felinae98** [comment]
在右侧也会有这个问题
![default](https://user-images.githubusercontent.com/23295345/47638726-560ded80-db9a-11e8-8bbb-d36706ecf150.png)

**Comment by grami-fr** [comment]
Like buoyancy99, i have the same bug (when the dock is at bottom). The bug happened this morning after an update .

**Comment by AlexandreMeiGomes** [comment]
> When clicking on wifi or volume, the dock tried to show secondary menu below the dock. But when the dock is at bottom, user cannot see them.
> 
> ![unnamed_1](https://user-images.githubusercontent.com/16475227/47626167-03272e00-dae7-11e8-9575-962c70023a34.png)

I also have the same problem here, it started to behave like this after the last update.

**Comment by gonesimera** [comment]
I have the same problem, it started after the latest update.

**Comment by antechdesigns** [comment]
Same here, the dock is full of bugs when placed at the bottom.

**Comment by antechdesigns** [comment]
Seems to be fixed after the latest update, good job guys, thanks ;)

**Comment by AlexandreMeiGomes** [comment]
Yes, now it's working fine for me too :D

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
