### ISSUE TITLE
Dock hangs after login

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/dde-dock#123]
After login, Deepin Dock 4.7.4 becomes unresponsive. After 30 seconds it crashes and reloads properly.

**Comment by es20490446e** [comment]
Fixed.

**Comment by es20490446e** [comment]
Still happening.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
