### ISSUE TITLE
Most plugins are missing after the update .

### ISSUE THREAD

**Issue by DmitrySkibitsky** [linuxdeepin/dde-dock#131]
There are only plugins "date and time" and " shutdown"

![deepinscreenshot_ - _20181123162706](https://user-images.githubusercontent.com/20288556/48948456-2fdf3180-ef3d-11e8-96c2-84bdfeaab102.png)

Version Dock: deepin-dock  4.8.1-1

**Comment by aiamuzz** [comment]
@DmitrySkibitsky  ... Yes that is to avoid duplication ... the team has decided to move the wireless and sound plugin into the system tray ...

**Comment by DmitrySkibitsky** [comment]
@aiamuzz 
Then where is this system tray?)) For as you can see the screen recording application was launched and I do not see this system tray.

![deepin-screen-recorder_select area_20181123184906](https://user-images.githubusercontent.com/20288556/48954032-843fdc80-ef50-11e8-8cde-22a261ac0617.gif)

**Comment by DmitrySkibitsky** [comment]
@aiamuzz this is fixed) Updated the package to the latest version. Thanks
