### ISSUE TITLE
file INSTALL cannot find

### ISSUE THREAD

**Issue by JoaquinDecima** [linuxdeepin/dde-dock#134]
`CMake Error at cmake_install.cmake:119 (file):
  file INSTALL cannot find
  "/home/pato/Proyectos/dde-dock-compiler/cmake/DdeDock/DdeDockConfig.cmake".
`
`make: *** [Makefile:74: install] Error 1
`

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
