### ISSUE TITLE
系统长时间不关机会出现卡顿(四天)

### ISSUE THREAD

**Issue by bibichuan** [linuxdeepin/dde-dock#136]
我的是戴尔Percision5820工作站，64G内存、NVIDIA Quadro P2000,512G固态（分了120G安装Deepin，剩下的是win）,CPU 是英特尔Xeon(R)W-2145 CPU @3.70GHZ x16，开机每超过4天，到第四天早上，系统就变得很卡，dock显示也不正常，必须重新启动dock才能解决问题，下面是两次的日志。这个问题可以说完全能重现，只要是开机超过四天。
[deepin-log-1543453482177.tar.gz](https://github.com/linuxdeepin/dde-dock/files/2684810/deepin-log-1543453482177.tar.gz)
[deepin-log-1544937641006.tar.gz](https://github.com/linuxdeepin/dde-dock/files/2684811/deepin-log-1544937641006.tar.gz)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
