### ISSUE TITLE
[Feature request] Zoom on dock

### ISSUE THREAD

**Issue by renidantass** [linuxdeepin/dde-dock#137]
Would be great zoom on apps on dock like Mac OS.

**Comment by aiamuzz** [comment]
@renidantass ...

by zoom on dock ... are you referring to the mouse-over magnification of the dock icons ?

**Comment by futterwaqckens** [comment]
Yes mouse-over magnification animation on the dde-dock would be awesome.

**Comment by futterwaqckens** [comment]
also 3d dock would be great too. I was useing plank but I couldent get the control center I con or shutdown to add to it.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
