### ISSUE TITLE
Wrong rendering in the dock.

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/dde-dock#138]
Hello, after the latest update i'm getting the next bug:
![deepin-screen-recorder_select area_20181226004311](https://user-images.githubusercontent.com/5034215/50426756-84acf980-08a7-11e9-9d81-9afdab6a8cf7.gif)

Why?

My setup:
██████████████████  ████████   joselito92@joselito-asus-rog 
██████████████████  ████████   ---------------------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: G771JW 1.0 
████████            ████████   Kernel: 4.14.90-1-MANJARO 
████████  ████████  ████████   Uptime: 1 hour, 33 mins 
████████  ████████  ████████   Packages: 1100 (pacman) 
████████  ████████  ████████   Shell: bash 4.4.23 
████████  ████████  ████████   Resolution: 1920x1080 
████████  ████████  ████████   DE: Deepin 
████████  ████████  ████████   WM: Mutter(DeepinGala) 
████████  ████████  ████████   Theme: deepin [GTK2/3] 
████████  ████████  ████████   Icons: Compass [GTK2/3] 
████████  ████████  ████████   Terminal: deepin-terminal 
                               Terminal Font: DejaVu Sans Mono 11 
                               CPU: Intel i7-4720HQ (8) @ 3.600GHz 
                               GPU: Intel 4th Gen Core Processor 
                               GPU: NVIDIA GeForce GTX 960M 
                               Memory: 6596MiB / 15933MiB 

Thanks!

**Comment by SiamSami** [comment]
I had the same issue. I fixed it by rebooting.

**Comment by MrP4p3r** [comment]
I have the same issue after some updates on my Arch. This issue does not seem to be related to dde-dock.

It always appears in the top-left corner after some updates (no matter where your dock is placed). Using `xprop` I found that this box was deepin welcome window (or some other deepin-thing which seems to be not installed on my system). Just use `xkill` + click on this box (maybe twice).

**Comment by ErikEklund** [comment]
xkill didn't work for me but `ps -aux | grep deepin-welcome` followed by `sudo kill <process id>` worked fine

**Comment by MrP4p3r** [comment]
Just updated and got this thing again. Indeed it does not get killed by xkill (but `pkill dde-welcome` does as well as the command in the comment above).

For some reason dde-welcome does not go in full-screen.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
