### ISSUE TITLE
Wrong rendering in the dock on fashion mode

### ISSUE THREAD

**Issue by joaomarccos** [linuxdeepin/dde-dock#140]
![deepin-screen-recorder_select area_20190105133642](https://user-images.githubusercontent.com/7428221/50726666-18c06180-10ef-11e9-834f-0f9ba1eb8414.gif)

**Comment by joaomarccos** [comment]
I reproduced this problem in all locations.

**Comment by SiamSami** [comment]
I don't understand the problem. Can you clarify it?

**Comment by joaomarccos** [comment]
Try a zoom on gif and you'll see some trash on dock corners.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
