### ISSUE TITLE
Hangouts icon duplicated in dock

### ISSUE THREAD

**Issue by ErikEklund** [linuxdeepin/dde-dock#141]
Distro: Antergos
Deepin version: Rolling, all latest packages installed
Dock version: 4.8.6-1

I'm using the Hangouts addon for chrome: https://chrome.google.com/webstore/detail/google-hangouts/nckgahadagoaajjgafhacjanaoiihapd

Whe using my computer normally (not interacting with hangouts at all), new icons appear regularly on the dock: https://i.imgur.com/qid0jto.png

Clicking any of the icons except the left one crashes the dock. After restart, the dock looks like this: https://i.imgur.com/3G1ssWq.png

Issue disappears after reboot, although new icons will start to appear after a while.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
