### ISSUE TITLE
[ArchLinux/ManjaroLinux] Onboard plugin does not show settings and board on screen

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/dde-dock#143]
Hello guys,

Thank you for this great desktop.

I'm getting this problem:
![deepin-screen-recorder_select area_20190209012203](https://user-images.githubusercontent.com/5034215/52510560-7aec1500-2c0d-11e9-8d85-83e6b0f8509d.gif)

Clicking on board icon or settings does not show anything.

Why?

```
 ██████████████████  ████████     OS: Manjaro 18.0.2 Illyria
 ██████████████████  ████████     Kernel: x86_64 Linux 4.14.94-1-MANJARO
 ██████████████████  ████████     Uptime: 4h 12m
 ████████            ████████     Packages: 1171
 ████████  ████████  ████████     Shell: zsh 5.6.2
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: Deepin 15.9
 ████████  ████████  ████████     WM: Deepin WM
 ████████  ████████  ████████     WM Theme: Qogir-gnome
 ████████  ████████  ████████     GTK Theme: Qogir-gnome [GTK2/3]
 ████████  ████████  ████████     Icon Theme: Dexter
 ████████  ████████  ████████     CPU: Intel Core i7-4720HQ @ 8x 3.6GHz [63.0°C]
 ████████  ████████  ████████     GPU: Mesa DRI Intel(R) Haswell Mobile 
                                  RAM: 6449MiB / 15933MiB
```

**Comment by Dio1453** [comment]
same problem. need help

**Comment by ToRvaLDz** [comment]
same here

**Comment by TeknoMobil** [comment]
No problem using Arch.
Install: sudo pacman -S onboard

**Comment by ToRvaLDz** [comment]
@TeknoMobil it seems that the icon appear in the dock also if the package is not installed. After installing with pacman it is working. Tnx

**Comment by BLumia** [comment]
Maybe we can add a check and remind user to install onboard if it's not installed?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
