### ISSUE TITLE
[Feature request] date plugin show today's date

### ISSUE THREAD

**Issue by mxbrandi** [linuxdeepin/dde-dock#146]
The date plugin only shows the current time. To view the current date, I have to mouse over the time string.

It would be great if we had an option to show the current date directly in the dock, without having to mouse over the time string.

**Comment by felixonmars** [comment]
You may want https://github.com/BLumia/dde-dock-pineappledatetime

**Comment by mxbrandi** [comment]
> You may want https://github.com/BLumia/dde-dock-pineappledatetime

Thanks a lot, that's exactly what I wanted :+1: 

However, I'll leave the issue open, as I would argue that this feature should be officially supported.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
