### ISSUE TITLE
deepin dde-dock memory overflow after refresh deepin 15.9.2

### ISSUE THREAD

**Issue by gilcierweb** [linuxdeepin/dde-dock#149]
deepin dde-dock memory overflow after refresh deepin 15.9.2 bug

**Comment by 74cmonty** [comment]
Confirm.
Additional high CPU load (40-70%).

**Comment by gilcierweb** [comment]
Yes, 0-100%, until you crash pc

**Comment by 74cmonty** [comment]
Where to open a bug for this issue?

**Comment by gilcierweb** [comment]
I did not understand the question, bug when updating deepin

**Comment by 74cmonty** [comment]
My question is:
Where can/must I open a bug for this issue?
Or is it sufficient to keep this issue here open?

Until now nobody from development has picked up this issue.
A bug could probably raise their attention.

**Comment by gilcierweb** [comment]
I think, it may be bug same, this occurred when upgrading to version mentioned.

**Comment by listenerri** [comment]
@electricface 这个估计跟论坛里的一样

**Comment by electricface** [comment]
run command:
```
sudo deepin-feedback-cli
```
then upload tar.gz file.

**Comment by gilcierweb** [comment]
had to format to solve the problem could not use pc.
I will do this.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
