### ISSUE TITLE
time and date plugin icon always shows time in 24-hour format

### ISSUE THREAD

**Issue by denseleznev** [linuxdeepin/dde-dock#15]
After recent update to dde-dock 4.0.0 in Arch Linux, time in dock is shown only in 24-hour format even the required settings in control panel are set to 12-hour format. I am not sure If it's considered to be changed somewhere by right-clicking on the widget, right now the widget is unclickable with both mouse buttons.

**Comment by oberon2007** [comment]
Looks like the analog clock has been dropped?

**Comment by sbwtw** [comment]
the new dock time plugin only have 24-hour format display, and no pointer mode

**Comment by sbwtw** [comment]
left click time item will open dde-calendar if you installed it. and right click has no action.

**Comment by ibrokemypie** [comment]
Is there any option to change this to twelve hour?

**Comment by andrewaclear** [comment]
I have this same problem. I have to right-click it twice to show 12-hour format, and then after I log back it goes back to 24-hour anyways.

**Comment by BLumia** [comment]
> I have this same problem. I have to right-click it twice and set it to 12-hour format for it to actually switch to 12-hour format, but then after I logout and then log back in it goes back to 24-hour anyways.

This issue is not for the problem you've got, refer to https://github.com/linuxdeepin/dde-dock/issues/236 . See https://github.com/linuxdeepin/dde-dock/pull/265 for a possible working patch, the v20 codebase got a bugfix for that issue but it seems the v20 code release will still take a while to be done.
