### ISSUE TITLE
What the ghost?

### ISSUE THREAD

**Issue by Rekols** [linuxdeepin/dde-dock#16]
main.o: In function `main':
/home/rekols/桌面/build-dde-dock-Desktop_Qt_5_7_0_GCC_64bit-Debug/frame/../../dde-dock-master/frame/main.cpp:42: undefined reference to `Dtk::Widget::DApplication::loadTranslator(QList<QLocale>)'
dockitem.o: In function `DockItem::showPopupWindow(QWidget*, bool)':
/home/rekols/桌面/build-dde-dock-Desktop_Qt_5_7_0_GCC_64bit-Debug/frame/../../dde-dock-master/frame/item/dockitem.cpp:190: undefined reference to `Dtk::Widget::DArrowRectangle::getContent() const'
dockpopupwindow.o: In function `DockPopupWindow::setContent(QWidget*)':
/home/rekols/桌面/build-dde-dock-Desktop_Qt_5_7_0_GCC_64bit-Debug/frame/../../dde-dock-master/frame/util/dockpopupwindow.cpp:33: undefined reference to `Dtk::Widget::DArrowRectangle::getContent() const'
dockpopupwindow.o: In function `DockPopupWindow::eventFilter(QObject*, QEvent*)':
/home/rekols/桌面/build-dde-dock-Desktop_Qt_5_7_0_GCC_64bit-Debug/frame/../../dde-dock-master/frame/util/dockpopupwindow.cpp:81: undefined reference to `Dtk::Widget::DArrowRectangle::getContent() const'
moc_dockpopupwindow.o:(.data.rel.ro._ZTV15DockPopupWindow[_ZTV15DockPopupWindow]+0x38): undefined reference to `Dtk::Widget::DArrowRectangle::event(QEvent*)'

**Comment by jouyouyun** [comment]
@sbwtw

**Comment by sbwtw** [comment]
you need to install new version of libdtkwidget-dev

**Comment by Rekols** [comment]
Have installed.

**Comment by sbwtw** [comment]
@Rekols version? the latest version is 0.1.3

**Comment by Rekols** [comment]
Where is libdtkwidget-dev

**Comment by Rekols** [comment]
deepin-tool-kit?

**Comment by sbwtw** [comment]
@Rekols are you using arch ? i don't know what package name arch uses, maybe is deepin-tool-kit @felixonmars

**Comment by Rekols** [comment]
I have compiled and installed deepin-tool-kit....

**Comment by felixonmars** [comment]
Yep, it is deepin-tool-kit.

**Comment by Rekols** [comment]
main.cpp:(.text.startup+0x16d)：对‘Dtk::Widget::DApplication::loadTranslator(QList<QLocale>)’未定义的引用
dockitem.o：在函数‘DockItem::showPopupWindow(QWidget*, bool)’中：
dockitem.cpp:(.text+0x45c)：对‘Dtk::Widget::DArrowRectangle::getContent() const’未定义的引用
dockpopupwindow.o：在函数‘DockPopupWindow::setContent(QWidget*)’中：
dockpopupwindow.cpp:(.text+0x363)：对‘Dtk::Widget::DArrowRectangle::getContent() const’未定义的引用
dockpopupwindow.o：在函数‘DockPopupWindow::eventFilter(QObject*, QEvent*)’中：
dockpopupwindow.cpp:(.text+0x4de)：对‘Dtk::Widget::DArrowRectangle::getContent() const’未定义的引用
moc_dockpopupwindow.o:(.data.rel.ro._ZTV15DockPopupWindow[_ZTV15DockPopupWindow]+0x38)：对‘Dtk::Widget::DArrowRectangle::event(QEvent*)’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:371: recipe for target '../../dde-dock/dde-dock' failed
make[1]: *** [../../dde-dock/dde-dock] Error 1
make[1]: Leaving directory '/home/rekols/桌面/build-dde-dock-Desktop_Qt_5_7_0_GCC_64bit-Release/frame'
Makefile:43: recipe for target 'sub-frame-make_first' failed
make: *** [sub-frame-make_first] Error 2



额。

**Comment by sbwtw** [comment]
@Rekols are you compile and install deepin-tool-kit from source code ? you are using old version header file, maybe you  are not installed d-t-k to right path.

**Comment by Rekols** [comment]
libdtkwidget-dev is already the newest version (0.1.1-1).

**Comment by Rekols** [comment]
Where is the latest version?

**Comment by sbwtw** [comment]
@Rekols 0.1.4

**Comment by Rekols** [comment]
@sbwtw  How to upgrade?

**Comment by Rekols** [comment]
@sbwtw   ok.
