### ISSUE TITLE
unmount button not working

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-dock#17]
When I have a partition mounted and I click on the eject button icon in the dock, the device window pops up. Clicking on the hightlighted eject icon there, nothing happens. Clicking any where in the little window has no effect ...

**Comment by oberon2007** [comment]
Might be connected to the fact that **deepin-filemanager** is unable to mount my other partition ;) I can do it without problem with **nautilus**.

**Comment by sbwtw** [comment]
@jouyouyun

**Comment by fasheng** [comment]
This was solved by https://cr.deepin.io/#/c/15502/ and test pass in arch.

**Comment by jouyouyun** [comment]
Unfortunately, this submission(#15502) will be reveted, because it was found to cause a serious bug:  can not mount the iphone device.
I will rewrite the mounts module to solve this bug.

**Comment by fasheng** [comment]
it doesn't matter, go ahead!

**Comment by oberon2007** [comment]
The eject issue seems fixed for me in any case. Thank you.
