### ISSUE TITLE
my network icon disapears for accident when i pull it do desktop

### ISSUE THREAD

**Issue by ciciolina** [linuxdeepin/dde-dock#182]
hi, the title say what happen... i install a fresh archlinux from zero, i install deepin complete and works amazing, but just before i can make a backup accidently i pull the network icon out of the dock and the icon its gone forever... i go to dconf and find the line but i press the default value and... dont work, please any person who has arch + deepin can please send me the line of dconf whitout modifications to repair my dock?

>> i  only need the custom value of the dde.dock, i think that can fix my problem and help more people that accidently pull out any plugin.
i put the screenshot of the route on dconf and you can see the network icon disappear too
![DeepinScreenshot_20190416184725](https://user-images.githubusercontent.com/49702606/56255586-1628bd00-608b-11e9-82b0-dc7c9d4f0049.png)
.

**Comment by k0rn1** [comment]
Mine just disappeared after an update.
Strangely since I am using Arch it says dde-dock is on its newest version, but `dde-dock -v` results in
```
"dtkwidget2" can not find qm files
"dde-dock" can not find qm files
dde-dock 2.0
```

**Comment by gquittet** [comment]
Same problem here. I've installed nm-applet temporarily.

![image](https://user-images.githubusercontent.com/11082739/56348535-ee3e7400-61c6-11e9-8b72-f270d4decb1a.png)

**Comment by justforlxz** [comment]
upload ~/.cache/deepin/dde-dock/dde-dock.log , thank you!

**Comment by gquittet** [comment]
Here you are: https://gist.github.com/gquittet/d7c6094350f2a634aeea748706340441 :)

**Comment by justforlxz** [comment]
> Here you are: https://gist.github.com/gquittet/d7c6094350f2a634aeea748706340441
> 
> My operating system:
> ![image](https://user-images.githubusercontent.com/11082739/56351353-36609500-61cd-11e9-9e48-7e0424078a9c.png)

hi, I see a error for libnetwork.so, maybe you need wait for the repo update for deepin-network-utils package.

**Comment by justforlxz** [comment]
```
 "SystemTray" load plugin failed!!! "Cannot load library /usr/lib/dde-dock/plugins/system-trays/libnetwork.so: (/usr/lib/dde-dock/plugins/system-trays/libnetwork.so: undefined symbol: _ZN3dde7network12NetworkModel23m_ConnectivitySecondaryE)" "/usr/lib/dde-dock/plugins/system-trays/libnetwork.so"
```

**Comment by gquittet** [comment]
Thank you very much for your help ! :+1:

**Comment by gquittet** [comment]
The problem is fixed! 🎉

**Comment by gquittet** [comment]
close
