### ISSUE TITLE
network connection issue

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-dock#19]
When attempting to connect to a new wifi, there is no dialogue to enter the password. Instead I get alternating messages, attempted connection / unconnected /attempting ... and so on
When I try the same from the control center after a while the dock will crash.
Connection to a known network where the password is already stored works ok.

**Comment by philmmanjaro** [comment]
Maybe stop the dock and start it again from a terminal to get some debug-output for analysis ...

**Comment by rejuvenator** [comment]
Same problem here. No way to input the password in the dock. In the control center, pressing the selected wifi spot results in attempting to connect, but no password prompt.

**Comment by oberon2007** [comment]
nothing in the terminal, but journalctl has something to say!
```
Sep 05 19:20:47 manjaro-deepin com.deepin.daemon.InputDevices[706]: <error> module.go:49: Invalid module name: launcher
Sep 05 19:20:47 manjaro-deepin com.deepin.daemon.InputDevices[706]: <error> module.go:49: Invalid module name: dock
Sep 05 19:20:47 manjaro-deepin com.deepin.daemon.InputDevices[706]: <error> module.go:49: Invalid module name: soundeffect
Sep 05 19:20:48 manjaro-deepin com.deepin.daemon.InputDevices[706]: <error> utils_bluez.go:89: org.bluez.Error.InProgress:Operation already in progress
Sep 05 19:20:48 manjaro-deepin com.deepin.daemon.InputDevices[706]: <error> module.go:49: Invalid module name: launcher
Sep 05 19:20:48 manjaro-deepin com.deepin.daemon.InputDevices[706]: <error> module.go:49: Invalid module name: dock
Sep 05 19:20:48 manjaro-deepin com.deepin.daemon.InputDevices[706]: <error> module.go:49: Invalid module name: soundeffect
Sep 05 19:20:50 manjaro-deepin com.deepin.daemon.InputDevices[706]: <error> module.go:49: Invalid module name: launcher
Sep 05 19:20:50 manjaro-deepin com.deepin.daemon.InputDevices[706]: <error> module.go:49: Invalid module name: dock
Sep 05 19:20:50 manjaro-deepin com.deepin.daemon.InputDevices[706]: <error> module.go:49: Invalid module name: soundeffect
Sep 05 19:21:05 manjaro-deepin daemon/launcher-daemon[4820]: launcher.go:585: MarkLaunched error: invalid id "deepin-menu"
Sep 05 19:21:22 manjaro-deepin daemon/launcher-daemon[4820]: launcher.go:585: MarkLaunched error: org.freedesktop.DBus.Error.ServiceUnknown:The name com.deepin.store.Api was not provided by any .service files
Sep 05 19:21:48 manjaro-deepin daemon/launcher-daemon[4820]: launcher.go:585: MarkLaunched error: org.freedesktop.DBus.Error.ServiceUnknown:The name com.deepin.store.Api was not provided by any .service files
Sep 05 19:31:11 manjaro-deepin kernel: QDBusConnection[5801]: segfault at 264a490 ip 000000000264a490 sp 00007efcdb0f7a38 error 15
Sep 05 19:31:11 manjaro-deepin org.a11y.atspi.Registry[741]: XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
Sep 05 19:31:11 manjaro-deepin com.deepin.daemon.InputDevices[706]: (dde-session-daemon:4853): Gdk-WARNING **: dde-session-daemon: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
Sep 05 19:31:11 manjaro-deepin pulseaudio[4810]: XIO:  fatal IO error 1 (Operation not permitted) on X server ":0"
Sep 05 19:31:11 manjaro-deepin NetworkManager[453]: <warn>  [1473096671.7573] error requesting auth for org.freedesktop.NetworkManager.wifi.share.protected: Authorization check failed: Refusing activation, D-Bus is shutting down.
Sep 05 19:31:11 manjaro-deepin NetworkManager[453]: <warn>  [1473096671.7574] error requesting auth for org.freedesktop.NetworkManager.wifi.share.open: Authorization check failed: Refusing activation, D-Bus is shutting down.
```
So doesn't look related to the dock acutally I think ...

**Comment by oberon2007** [comment]
Here's more:
[journalctl_errors.txt](https://github.com/linuxdeepin/dde-dock/files/455530/journalctl_errors.txt)

**Comment by sbwtw** [comment]
@fasheng

**Comment by fasheng** [comment]
Well, I didn't realized this before, maybe caused by the latest network manager 1.4 in arch...

**Comment by oberon2007** [comment]
Yes, I was also suspecting **networkmanager**, which also gave some other headaches here. @philmmanjaro we also had a dbus update recently. Could that be related, too?
So you can reproduce this @fasheng ? I know it's easy to miss since the issue doesn't show as long as you use your known network. I also didn't realize it...

**Comment by philmmanjaro** [comment]
@oberon2007: In **stable** branch we still have the old **dbus** and **networkmanager**. Did you checked the ISOs you have created when built with **stable**? Please double check that to narrow it down.

**Comment by philmmanjaro** [comment]
@oberon2007: it would be good to recompile the package for the old networkmanager in stable. Also check with **unstable**. There we have newer packages of both, dbus and networkmanager.

**Comment by philmmanjaro** [comment]
**dbus 1.10.10** they (Arch) removed **x-server-autolaunch**. Please also try **dbus-x11** from **unstable**.

**Comment by fasheng** [comment]
Yes, it was caused by network-manager 1.4.1, this is really an unatable version, the official nm-applet is even broken here. I'm not sure if is an upstream issue, because i could not reproduce it all the time...



2016年9月6日 12:39, 12:39，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
@philmmanjaro yesterday I've already tried several combinations. ISO on stable branch aswell as my install on unstable, libdbus, dbus, dbus-X11, nothing worked. So really might be caused by nm. On Manjaro we currently have a different version than arch, though... But still, it's a new package.

**Comment by oberon2007** [comment]
@fasheng Which dde packages actually on **networkmanager**? I've just checked with ``pactree``: Neither **deepin-dock** nor **control-center** do ...

**Comment by oberon2007** [comment]
**dbus** seems to make more sense maybe. In any case: If I'd like to recompile against our stable branch, which deepin packages would make sense?

**Comment by fasheng** [comment]
It's deepin-daemon, the backend of dock and control center. Besides, could you fall back to network manager 1.2.4 temporary, i just have no idea for 1.4.1-dev in short time :(



2016年9月6日 19:42, 19:42，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by oberon2007** [comment]
In that case I think recompiling against our stable branch will not make much sense. There we have already networkmanager-1.2.5dev+9+g299feed, too - whatever exactly that version is :wink: 
To fall back I don't have an idea how we could do that - For the ISOs I could try including a dedicated package **networkmanager-deepin** or so, but then how to get rid of it later. I could just later convert it into a metapackage depending on networkmanager, but that feels fishy... Any ideas, @philmmanjaro ?

**Comment by philmmanjaro** [comment]
@oberon2007: did you recompile the package against the NM shipped in our stable branch?

**Comment by oberon2007** [comment]
@philmmanjaro I will try this in a minute. Sofar I have tried the current deepin packages with **networkmanager** downgraded to **1.4.0**. That's better but it still has an issue: I can now enter a password in the control center, but it will still not connect and when I open control center again the password field is empty again, @fasheng ?

**Comment by philmmanjaro** [comment]
@oberon2007: **v1.2.5-dev** is the latest package in **v1.2.x** series. It should work. Did you already tried it? **v1.4.0** has different issues with **WIFI** drivers. That is why Arch pushed it to latest **v1.4.x** development release. So my only question is: does it work with the current **v1.2.x** release we have in **stable** branch or not. 

Else you have to create a new package with the version working for **deepin**, create a new package for **dde-dock** which depends on it. When Arch-Upstream fixed it and your **dde-dock** is in a lower version as Arch has, you can delete both packages you have created from our overlay. The deepin networkmanager package should have a provides line as usual.

**Comment by oberon2007** [comment]
Since @fasheng suggested that actually **deepin-daemon** ist the package that needs to interact properly I've just tried to build that one, but interestingly I am not able to build the package in any of our branches. Some things are a little strange here, so I wonder, if actually we have a problem here with **deepin-daemon** itself.
When I use @felixonmars 's [sources](https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/deepin-daemon):

- checksum for **polkit-gnome-authentication-agent-1-deepin.desktop** doesn't match ?
- _deepinapiver=3.0.12 in the PKGBUILD while the current **deepin-api** package is actually at **v3.0.13** ?
- When I try to build the pkg I run into this:
```
gopath/src/pkg.deepin.io/dde/daemon/mpris/manager.go:18:2: no buildable Go source files in /build/deepin-daemon/src/build/src/dbus/org/freedesktop/dbus
make: *** [Makefile:46: out/bin/dde-session-daemon] Error 1
```

**Comment by oberon2007** [comment]
Ok. I admit the [one commit](https://github.com/linuxdeepin/dde-api/commit/a894510400498c37f8cdeeeaaa485c5458702027) between **dde-api 3.0.12** and **3.0.13** will certainly not be the root of the issue :laughing: 
I'll investigate more into dbus versions now ... ``no buildable Go source files in /build/deepin-daemon/src/build/src/dbus/org/freedesktop/dbus``

**Comment by oberon2007** [comment]
Hm strange. With **makepkg** I am able to build deepin-daemon, but with **buildpkg** in the chroot I see the above error. Something seems to be different on my actually installed Deepin system...

**Comment by oberon2007** [comment]
So. I have now tried to get this to work (on unstable branch) with a re-compiled **deepin-daemon** (in stable it seems I can't compile it because of the wrong dbus version).
In any case, no matter which version of **networkmanager**, I get the same or at least similar issues with authorization in the **control-center**. I have tried **nm** **v1.4.1dev+38+gfe0e507**, **v1.4.0**, **v1.2.5dev+9+g299feed** and **v1.2.4** - no luck.
Also disabling ``scan-rand-mac-address`` doesn't make any difference.
Using **wicd** works fine, but I think for deepin that's not an option because it cooperates neither with **deepin-dock** nor with **control-center** and there will just be no entries in those places ...
I guess we'll just have to wait a little until a proper solution comes up.

**Comment by oberon2007** [comment]
Maybe this might additionally be helpful:
When I run nm-applet from the terminal and try to connect to a new network I get
```
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
```

**Comment by felixonmars** [comment]
@oberon2007 

The checksum of `polkit-gnome-authentication-agent-1-deepin.desktop` still matches here, so I am not sure why it doesn't validate for you. I have zero knowledge about **buildpkg**, so I can't help with that either.

The one commit between dde-api 3.0.12 and 3.0.13 doesn't affect other components so I did not rebuild for it.

The last message indicates a missing `gnome-keyring` package in the dependency chain. I'll fix it soon.

**Comment by fasheng** [comment]
@oberon2007 
Maybe I misunderstand you before, the deepin-daemon just depends on the DBus interface of NetworkManager, so you don't need to recompile deepin-daemon, just downgrade NetworkManager is OK.

And you said both NetworkManager **1.2.4** and **!.2.5dev** could reproduce the wifi secrets popup issue, but they are all fine here, and I could only reproduce it under NetworkManager **1.4.1dev+33+gc87b89b**...

Here is my testing seteps:
1. Remove the target wifi profiles through nmtui, dde-control-center or remove them manually in **/etc/NetworkManager/system-connections/**
1. Install target NetworkManager version (**1.2.4/1.2.5dev/1.4.1dev**)
1. Restart NetworkManager
1. After a while, try to connect the wifi through dock or control-center and to see whether the secrets dialog will popup

And the results are:
1. NetworkManager 1.2.4 works fine
1. NetworkManager 1.2.5dev works fine
1. NetworkManager 1.4.1dev will not popup the secrets dialog sometimes

**Comment by philmmanjaro** [comment]
I've updated **NetworkManager 1.4.1dev** once again on our end. Please check again.

**Comment by oberon2007** [comment]
Thank you @felixonmars Maybe it was as simple as that? **gnome-keyring** was (surprisingly) not installed on my running system - no idea how it had worked in the past. With this now installed and @philmmanjaro updated **networkmanager** package everything works for me on the unstable branch. I'll check what I can do in stable, later. In any case I'll just add **gnome-keyring to the packages list and if necessary I'll create a **networkmanager-deepin** package that works with the deepin packages currently there.

**Comment by philmmanjaro** [comment]
@oberon2007: so it was an missing dependency after all? keep me updated on the process.

**Comment by oberon2007** [comment]
Looks as if it was as simple as that after all :laughing: Seems to works for me on stable branch as well with **nm** version currently there. @fasheng probably **gnome-keyring** simply dropped **gnome-keyring** dependency recently?

**Comment by fasheng** [comment]
Yes, as Felix mentioned, gnome-keyring is required, too :)



2016年9月7日 14:30, 14:30，在 Bernhard Landauer <notifications@github.com> 已写:

**Comment by felixonmars** [comment]
I have uploaded deepin-daemon 3.0.20-2 with **gnome-keyring** added in the depends array.

**Comment by oberon2007** [comment]
Thank you :)

**Comment by alexandre1985** [comment]
I'm using Manjaro Deepin 17.0.1 x86_64 and when I try to connect to a wifi that has password encryption the dialog for entering the password doesn't pop-up.
I have to configure the password through the Control Center and I can see that the password is blank. I then enter the password in there and try to connect to the wifi network and the connection is successful.
It would be great if the dialog for the password would pop-up in case the password was blank.
Is there a way to achieve this?
(I checked and I have gnome-keyring installed)

**Comment by oberon2007** [comment]
@alexandre1985 have a look at the workaraound [here](https://github.com/linuxdeepin/developer-center/issues/246#issuecomment-298585523)

**Comment by alexandre1985** [comment]
Thank you @oberon2007 . It did work :)

**Comment by oberon2007** [comment]
Great! :)
