### ISSUE TITLE
Status "Keep Shown" shows the background image in the background instead of the running app

### ISSUE THREAD

**Issue by ivkovici** [linuxdeepin/dde-dock#197]
Deepin edition: 15.10 Desktop

I made a screencast about the problem.

![deepin-screen-recorder_Select area_20190509194310](https://user-images.githubusercontent.com/10272924/57475623-f9039a80-7294-11e9-949f-c887ac8e477a.gif)

**Comment by Stoope** [comment]
@ivkovici It's how it should works. Why do you think it's wrong behavior?

**Comment by ivkovici** [comment]
For me, it seemed logical that "Keep Shown" should look like "Smart Hide" on pulled down cursor. Also, I think it looks better that way. But if you are saying that it's not a bug, I can close the issue.

**Comment by Stoope** [comment]
@ivkovici For me "Keep Shown" means dock preserve all space from bottom line. Dock shouldn't hide content of maximized windows behind it. Mac os dock do the same thing and I think it more logical for people to see when they decide to try deepin

**Comment by ivkovici** [comment]
Sorry, I was not familiar with the Mac OS dock. I checked out some pictures about it, and you're right. I'm closing the issue, but I would be happy if you would consider adding another option which would keep the dock shown in the smart hide option style. Anyway, Deepin is the best OS I used so far, keep up the good work! Thanks.
