### ISSUE TITLE
adjust sound with mouse-wheel not working

### ISSUE THREAD

**Issue by oberon2007** [linuxdeepin/dde-dock#20]
Looks like an over-flodding of signals is triggered when using the mouse-wheel on the dock icon to adjust the system volume. Constant beeping, delayed changes of the volume and the system becomes unresponsive up to the point that you have to quit the session to stop it.

**Comment by dodog** [comment]
yes, I can confirm. I tried  to downgrade from deepin-dock-4.0.3-1 to 
deepin-dock-4.0.2-1 and deepin-dock-4.0.1-1, but the problem persist. 
Downgrading to deepin-dock-4.0.0-1 works ok, but you have to click once and than scroll. 
I tried even deepin-dock-3.0.11-1, but the dock is not fully loaded using current config.

**Comment by sbwtw** [comment]
affected by other programs, like control-center sound module

**Comment by oberon2007** [comment]
https://github.com/linuxdeepin/developer-center/issues/123
