### ISSUE TITLE
其他平台（fedora,arch等）平台编译和编写插件的问题。

### ISSUE THREAD

**Issue by Quanyu-Mars** [linuxdeepin/dde-dock#200]
在其他平台编译dde-dock，有没有相关的wiki，cmake依赖的DtkWidget都没有，举步维坚。
如果用其他平台(如上）写插件，没有依赖的的dde-dev包如何解决

**Comment by BLumia** [comment]
arch 上是有的吧，比如你提到的 DtkWidgetConfig.cmake [就在 `dtkwidget` 包中](https://www.archlinux.org/packages/community/x86_64/dtkwidget/)，fedora 我就不清楚了。

**Comment by BLumia** [comment]
超一周没回复，先关掉了，如果依然有问题的话可以直接继续回复这个 Issue 告诉我们 :)
