### ISSUE TITLE
order of dock entries inconsistent

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/dde-dock#21]
The standard dock entries like network, logout, tray, sound do not keep their order., They are arranged apparently deliberately with every login and will not remember any sorting applied during the session.

**Comment by sbwtw** [comment]
this feature will be added in the next version

**Comment by DasJott** [comment]
Still the same here. Re-ordered the icons for wifi, lan , audio and stuff but it somehow gets randomly mixed up again. :(

Using Arch Anywhere.

**Comment by smartsmallking** [comment]
Sorry to reply you so late, this feature is currently supported
