### ISSUE TITLE
Wi-Fi not connecting through the deepin dock

### ISSUE THREAD

**Issue by cyberShaw** [linuxdeepin/dde-dock#219]
+ OS Version : Manjaro 18.0.2, Deepin Edition
+ Kernel Version : Linux 4.19

Steps to Reproduce : 
-----------------------
+ Open the Wi-Fi Menu in the dock
![photo_2019-06-15_20-20-20](https://user-images.githubusercontent.com/34317373/59552939-09511880-8fab-11e9-98d6-95c22e581070.jpg)
+ Connect to any Wi-Fi network by entering the password
![photo_2019-06-15_20-20-08](https://user-images.githubusercontent.com/34317373/59552944-1c63e880-8fab-11e9-97a0-0d554148be22.jpg)
+ Even if you enter the correct password, it shows an authentication error
![photo_2019-06-15_20-20-25](https://user-images.githubusercontent.com/34317373/59552953-3b627a80-8fab-11e9-9a5a-b9b2a7de5cd1.jpg)

Steps to Fix temporarily :
----------------------------
+ Open Terminal 
+ Enter the command, ```sudo systemctl restart NetworkManager```

**Comment by hfutxqd** [comment]
same issue here.

**Comment by Yoowhi** [comment]
I have the same error, but restart nm doesn't help.
NetworkManager's applet does work correctly.
Arch Linux, kernel 5.4.6

**Comment by 0yanghongwei** [comment]
@hfutxqd @Yoowhi @cyberShaw  Hello, any questions now? I don't have that at the moment.

**Comment by cyberShaw** [comment]
> @hfutxqd @Yoowhi @cyberShaw  Hello, any questions now? I don't have that at the moment.

I had that bug 2 years ago, haven't used it now

**Comment by 0yanghongwei** [comment]
@cyberShaw Thank you very much! The latest version no longer has this problem, so I'm going to turn it off. If you have any questions or good suggestions, please let us know.

**Comment by cyberShaw** [comment]
> @cyberShaw Thank you very much! The latest version no longer has this problem, so I'm going to turn it off. If you have any questions or good suggestions, please let us know.

Sure thing!
