### ISSUE TITLE
Seperator request..

### ISSUE THREAD

**Issue by thedeli** [linuxdeepin/dde-dock#23]
Hello. I'm using DDE on Arch and ı'm loving it :) perfect de for me. But I would like the option of seperating applications. just a line works for me. One other thing to mention is when I update a program 'even deepin application like deepin-terminal' dock is undocking application. Not a big issue :) I can dock it again but I guess it would be good for you to know. Thanks for your hard work...

**Comment by manateelazycat** [comment]
@sbwtw @hualet Update application should undock application icon from dock, just uninstall will.

**Comment by hualet** [comment]
It's a bug and a bug that not easy to fix if I remember it correctly.
@electricface

**Comment by SalahAdDin** [comment]
Isn't a good behavior.

**Comment by smartsmallking** [comment]
Sorry to reply to you so late, this question no longer exists
