### ISSUE TITLE
clock its broken in the last update.  I set  the clock 12h and the system change to 24h

### ISSUE THREAD

**Issue by ciciolina** [linuxdeepin/dde-dock#236]
hi, the last update of dde-dock [4.10.7-1] has the clock broken, always i have the clock set on 12h [AM-PM Format], but this new version set the clock on 24h format, nothing works when i try to set in the default format i have before the update.

I try this before i found the temp solution:
- force date format to -r
- set 24h to false via dconf editor
- mod the LC_TIME 

Nothing of this works... after this i try to downgrade the package and Voila! the clock works again on 12h format like always.

**This is the clock before the last update of dde-dock [4.10.7-1]**
https://imgur.com/a/YEjXpLu

my system its:
- ArchLinux [Kernel: 5.1.16-arch1-1-ARCH]
- DE: Deepin [rolling]
- Last updates of all Deepin package

* Please can you fix the dde-dock [4.10.7-1] to work again (clock 12h) like deepin-dock-4.10.5-2-x86_64 ?
Thanks

Pd. The temporal solution its downgrade!  try this on terminal:
sudo pacman -U /var/cache/pacman/pkg/deepin-dock-4.10.5-2-x86_64.pkg.tar.xz

**Comment by pedro-gaspar** [comment]
Hello, using Deepin 15.11 and my problem is the opposite. I try to change the clock to 24h but after reboot, it returns to 12h.

**Comment by BLumia** [comment]
assoc: https://github.com/linuxdeepin/developer-center/issues/1454

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
