### ISSUE TITLE
Icon issues of  dde-dock fashion mode

### ISSUE THREAD

**Issue by ceyhunnabiyev** [linuxdeepin/dde-dock#24]
I  use latest Archlinux  Deepin DE , but I have some questions for you according to dde-dock:
1. When I am clicking an  icon in dde-dock , there is no animation, or any reaction  that I clicked the icon (just wait until application opened);
2. Right click of mouse on area indicating to an application icon - open dock menu, not application context menu(except: mouse right click on the application icon);  
   ![screenshot from 2016-10-12 17 13 59](https://cloud.githubusercontent.com/assets/5506156/19311639/4c14bada-90a0-11e6-90cf-ff3937bfccd2.png)
3. How minimizing all windows indicating to one application

---

Thanks for attention to my questions, I loved  your great hark work 
Sorry for my issue title, I use  efficient mode dde-dock .

**Comment by sbwtw** [comment]
1. startup animation will added in 15.4
2. its feature, if not, you have no way to shown dock config menu (in fasion mode)
3. @sonald ?

**Comment by ceyhunnabiyev** [comment]
I am sorry  for that..  All question related to efficient mode, not fashion mode.. I use efficient mode  In second question  I have shown  the preview (except google chrome icon, on its area it opens dock menu not google chrome  context menu like 'New Window ', 'New Private Window', 'Close All' and etc.  )
