### ISSUE TITLE
[bug] dde-dock blur effect doesn't work in some scenarios.

### ISSUE THREAD

**Issue by ASparkOfFire** [linuxdeepin/dde-dock#242]
Blur effect doesn't work on dock after restarting computer.
My laptop has Intel HD 4400
A temporary workaround is switching off the window effect and then re-enabling the window effect.
![DeepinScreenshot_20190720161540](https://user-images.githubusercontent.com/26483873/61577923-f2529880-ab0b-11e9-8204-fe531d7774ad.png)

**Comment by ASparkOfFire** [comment]
@BLumia Please have a look its very annoying. :disappointed:

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
