### ISSUE TITLE
时间插件，你分配两次内存干啥？？？

### ISSUE THREAD

**Issue by pp710680429** [linuxdeepin/dde-dock#244]
![image](https://user-images.githubusercontent.com/10095765/61784469-53e07300-ae3c-11e9-97a3-258a06c94b33.png)

**Comment by BLumia** [comment]
cc @justforlxz

**Comment by BLumia** [comment]
@justforlxz 说大概是之前 rebase 的时候解决冲突导致的。

欢迎 Pull Request ，我可以帮忙 review 和合并。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
