### ISSUE TITLE
Keyboard switcher not showing in tray 

### ISSUE THREAD

**Issue by dimti** [linuxdeepin/dde-dock#246]
On dde-dock version 4.10.2 work perfectly.
![image](https://user-images.githubusercontent.com/582144/62275240-361d9a00-b44a-11e9-9c09-9d6ca48b418a.png)

On version 4.10.8 not work - keyboard layout indicator not showing in the tray in dock.
![image](https://user-images.githubusercontent.com/582144/62275393-83017080-b44a-11e9-9021-521c762f3436.png)

Some bug describe on manjaro forum https://forum.manjaro.org/t/deepin-current-keyboard-layout-indicator-missing/96310/2

What is the commit between versions 4.10.2 and 4.10.8 maybe potencialy broken keyboard switching indicator on archlinux/manjaro with deepin desktop env?

![image](https://user-images.githubusercontent.com/582144/62275331-62d1b180-b44a-11e9-967e-aeca18b6eab4.png)

**Comment by MetaiR** [comment]
I have this problem for a while and I think would be resolved by updates but it is not so, please fix it

**Comment by dimti** [comment]
Major release deepin-dock-5.0.0 no resolve this problem

**Comment by MetaiR** [comment]
yeah, no improvement or fixing after several updates; last time I had a problem with dde-dock (which was about GPU and showing items menu on right-click event) it took years to fix. so I am losing hope and think about migrating to other desktops like gnome or etc

**Comment by BLumia** [comment]
Not quite sure but this tray is more likely not provided by dde-dock, on my computer I use fcitx and it provide the correct tray...

**Comment by listenerri** [comment]
@BLumia The keyboard indicator is provided by dde-dock tray plugin with IndicatorTray type, if I remember correctly : )

**Comment by BLumia** [comment]
> @BLumia The keyboard indicator is provided by dde-dock tray plugin with IndicatorTray type, if I remember correctly : )

Thanks for the info! Hope the project maintainer have time to looking into this issue :)

**Comment by amiralisalimi** [comment]
I also have this problem. Some times it reappears and after restart, gone again. Deepin is (unfortunately) so bugy!!

**Comment by Luummii** [comment]
And I have this problem also.

**Comment by v-svg** [comment]
https://bbs.deepin.org/forum.php?mod=viewthread&tid=188564&page=1#pid660058

**Comment by Truden** [comment]
The solution of @v-svg worked for me with 500 delay.
Thank you.
