### ISSUE TITLE
No dde-dock over xrdp

### ISSUE THREAD

**Issue by svatopluk-svarc** [linuxdeepin/dde-dock#249]
When I connect to Deepin 15.11 over xrdp from Windows Remote Desktop, I can use dde-desktop, but dde-dock cannot be seen. When I open Terminal from menu on desktop, I can see that /usr/bin/dde-dock is running.
If I try: `execute pkill dde-dock & dde-dock`
error occurs:
```
No protocol specified
QXcbConnection: Could not connect to display: 10.0
```
Control center can be launched from desktop menu, but only window with no content is diplayed.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
