### ISSUE TITLE
Not display the pop-up preview windows

### ISSUE THREAD

**Issue by bigbruno** [linuxdeepin/dde-dock#25]
Dde-dock in Deepin 15.3 does not display the pop-up preview windows when mousing over.

It is very difficult to use the Deepin among the people I know and being necessary to reinstall Deepin 15.2 disabling updates.

Please add the option to back up the pop-up windows when you hover over the dde-dock.

**Comment by rafael-neri** [comment]
DDE Desktop Environment is beautiful but this problem also occurs on my computer.
I hope you fix it as soon as possible.

**Comment by rafepel** [comment]
This bug also affects my system. I like Deepin but if it continues I will have to migrate. Please resolve this.

**Comment by arraisfilho** [comment]
The model used up to version 15.2 is the best, it is possible to provide the two ways, so that we can choose one of the two?

**Comment by rafael-neri** [comment]
Other users are with the same complaint forum.
https://en.bbs.deepin.org/forum.php?mod=viewthread&tid=31530

**Comment by bigbruno** [comment]
Perhaps the best solution is to keep the current position using the mouse wheel, but when the mouse to display the pop-up preview windows.

After all now appears a pop-up with the program name, a little more and have the resources of 15.2 and 15.3

**Comment by talesam** [comment]
I agree, 15.2 Deepin dock version was better. Could return the old dock windows display.

**Comment by sbwtw** [comment]
hi, all. window preview will be back at 15.4, please wait.

**Comment by bigbruno** [comment]
Window preview not present in 15.4 beta, this feature no more added in 15.4?

**Comment by karev** [comment]
there is still no window preview in 15.4 beta

**Comment by bigbruno** [comment]
Thanks for adding this feature, would it be possible to add via dconf the option of how many ms to wait before displaying the pop up?

I prefer and believe that many others a pop up presentation faster, something like 50 or 100 ms, if it is configurable is even better.

**Comment by smartsmallking** [comment]
Sorry to reply to you so late, this question no longer exists.
