### ISSUE TITLE
Icons not loading correctly

### ISSUE THREAD

**Issue by pavansrinivasmamidala** [linuxdeepin/dde-dock#251]
I installed deepin desktop in manjaro and everything's working fine except the dock this is the image.
![DeepinScreenshot_20190901221513](https://user-images.githubusercontent.com/31120424/64079654-c9771300-cd07-11e9-97f8-b4ba5060bbbd.png)

There are other problems too like no icons in Deepin File Manager and Music notification is bizarre with a different font maybe I need to install a font or icon theme that will get this working.

Suggestions needed.

**Comment by BLumia** [comment]
I'm not quite sure since the icon is just `QIcon::fromTheme` calls, try `killall dde-dock` (it will launch again) and see if it restore normal?

@hualet any suggestions?

**Comment by pavansrinivasmamidala** [comment]
Don't bother I reinstalled it and everything works fine. but I'm curious to know what the problem is?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
