### ISSUE TITLE
Problem with serbian translation on dde-dock

### ISSUE THREAD

**Issue by Fuleron** [linuxdeepin/dde-dock#253]
Hello, I am Serbian translator, translating Deepin project https://www.transifex.com/user/profile/3acejax  . There is an issue on dock where AM and PM are located in English version.. Translations in Serbian are too long and don't fit properly in GUI. But the strings on Transifex are nonexistent. Can someone please upload those strings so I can shorten them to fit?
![ДипинСликаЕкрана_изабери-површину_20190917213832](https://user-images.githubusercontent.com/55282684/65179078-618c3080-da5a-11e9-8945-8fc1fcceeab9.png)
This is ugly and annoying..

**Comment by BLumia** [comment]
cc @zhuxiujuancindy

**Comment by hugok79** [comment]
Hello,
I am the Portuguese Coordinator/reviewer/translator in deepin transifex.
This also happens in Portuguese when I leave the clock in 12-hour mode
![DeepinScreenshot_selecione a área_20190922221124](https://user-images.githubusercontent.com/16929048/65394467-7d5b4380-dd86-11e9-871f-4da41c870210.png)

**Comment by zhuxiujuancindy** [comment]
Discussed with our developer, it cannot be changed on dde-dock.
The translation is from qt project.

**Comment by Fuleron** [comment]
Thank you.. Sorry for bothering you again @zhuxiujuancindy

**Comment by hugok79** [comment]
Thanks.
