### ISSUE TITLE
Show / Hide animation imporvements

### ISSUE THREAD

**Issue by AlexWoroschilow** [linuxdeepin/dde-dock#254]
Hi guys,
as you can see at the gif below, there are some rendering artifacts. 
I could reproduce it at 3 different laptops with an intel-graphics.
Please help

Deepin 15.11 stable
dde-dock 2.0

![deepin-screen-recorder_Select area_20190923015827](https://user-images.githubusercontent.com/3255923/65396346-bf47b200-dda5-11e9-9f61-17ccf543ec13.gif)

I actually figured out what is wrong with the animation. 

To understand how does it work i changed the 
WA_TranslucentBackground to WA_NoSystemBackground and now at the picture below we can see how the animation is actually working here. 

![deepin-screen-recorder_Select area_20191013022515](https://user-images.githubusercontent.com/3255923/66709358-81b1c580-ed62-11e9-96ce-0ab96dac956d.gif)

It is like the animation is happening inside the window frame instead of to move the window frame. 

To fix it one need to add a new window flag: Qt::X11BypassWindowManagerHint and change the animation logic as well. 

As we can see, this is not the rendering artifacts but the strange way to animate the dock. 

I actually already tried this approach and it does the work well. 
As one can see at the picture below, it works like a charm.

![deepin-screen-recorder_Select area_20191013024326](https://user-images.githubusercontent.com/3255923/66709390-71e6b100-ed63-11e9-9030-6c1dde3c70bd.gif)

**Comment by AlexWoroschilow** [comment]
this problem was solved in the PR:
https://github.com/linuxdeepin/dde-dock/pull/199

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
