### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/dde-dock#255]
On startup dde-dock and window-effects are missing.

If I start manually in terminal, this is what I get:
```
~$ dde-dock
translatePath after feedback: "/usr/share/libdtk-2.1.1/DWidget/translations/dtkwidget_de"
translatePath after feedback: "/usr/share/dde-dock/translations/dde-dock_de"
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
2019-09-23, 11:38:29.917 [Debug  ] [dapplication.cpp     Dtk::Widget::DApplicationPrivate::setSingleInstanceByDbus 212] register service failed: QDBusError("", "")
2019-09-23, 11:38:29.917 [Debug  ] [                                                         0] set single instance failed!
```

Several restarts didn't do a thing and downgrade the kernel neither.
Using arch linux with kernel 5.3.1 on Dell XPS 13 (all Intel stuff).

**Comment by BLumia** [comment]
Not quite sure about the failed to start reason but for the window effects please refer to https://github.com/linuxdeepin/developer-center/issues/1552 :P

**Comment by DasJott** [comment]
Installing deepin-kwin did the trick. Everything is back to normal!
