### ISSUE TITLE
Taskbar-menu disappears when start-menu is open

### ISSUE THREAD

**Issue by brainybrain** [linuxdeepin/dde-dock#257]
Just a minor issue...

![deepin-screen-recorder_Select area_20190928161205](https://user-images.githubusercontent.com/55926825/65820758-30b3b480-e22d-11e9-8737-768a84bb47f8.gif)

**Comment by fowger** [comment]
Hello man, install **deepin-dde** package and verify this problem happen!

**Comment by brainybrain** [comment]
> Hello man, install **deepin-dde** package and verify this problem happen!

Hello brother, I am using Deepin 15.11, I suppose the deepin-dde package is already installed? Or did I get something wrong...

**Comment by fowger** [comment]
Fine, I'm using Arch Linux, but it resolved as soon as I installed this package.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
