### ISSUE TITLE
can't update apt-get

### ISSUE THREAD

**Issue by OmarMohammed88** [linuxdeepin/dde-dock#260]
when I run this command "sudo apt-get update" I got this error,
" N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://repo.mongodb.org/apt/debian buster/mongodb-org/4.2 InRelease' doesn't support architecture 'i386' "

**Comment by BLumia** [comment]
I believe there is nothing related to the `dde-dock` project.

**Comment by OmarMohammed88** [comment]
ok thanks a lot, I fixed it
