### ISSUE TITLE
dock栏音量调节滑块中心定位问题

### ISSUE THREAD

**Issue by qiuzhiqian** [linuxdeepin/dde-dock#264]
dock栏中的音量调节滑块定位的时候好像不是把滑块中心定位到鼠标坐标位置，而是把滑块最左侧边沿定位到了鼠标坐标上，这样导致鼠标位置和滑块的位置有较大的偏移。刚开始以为是屏幕缩放导致的像素缩放偏移，结果我把缩放调整为100%这个显示问题仍然存在。

在控制中心中进行音量调节时就没有这个问题，鼠标位置正好就是滑块中心。

[环境]
OS:Archlinux
kernel:5.5.8
deepin-control-center:5.0.0-1
deepin-dock:5.0.0-5

**Comment by 0yanghongwei** [comment]
@qiuzhiqian 你好，现在还有问题吗？如果有，可否截图说明一下？

**Comment by qiuzhiqian** [comment]
@0yanghongwei 嗯，我目前的环境已经更换掉了。所以也不太确定这个问题现在具体是什么样的状态。如果你们那边能够确认对该问题进行了改善，可以把这个问题关掉哈

**Comment by 0yanghongwei** [comment]
好的。感谢你的帮助！

**Comment by smartsmallking** [comment]
看了下，应该没有这个问题了，目前是跟随鼠标中心点的，如果还有问题，可以重新这个issue
