### ISSUE TITLE
开机首次启动时控件位置不对

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/dde-dock#269]
当前设置为高效模式/左侧，首次开机启动 dde-dock 时控件位置均不对：

![2020-05-02-170604-974b0d](https://user-images.githubusercontent.com/1006477/80866608-304b3280-8cc2-11ea-8246-2cb4bdcee3f1.png)

右键进行任何设置（如放到屏幕另一边缘、切换时尚模式等）均可恢复正常，之后还原为高效模式/左侧也正常。

**Comment by smartsmallking** [comment]
现在没有这个问题了，如果还有，可以再打开这个issue
