### ISSUE TITLE
Sound volume improvement

### ISSUE THREAD

**Issue by bigbruno** [linuxdeepin/dde-dock#27]
Sound in Linux 100% has been recognized for many years as down.

Using the "dde-control-center" you can increase the volume to 150%, but the plugin for dde-dock the limit is 100%, it would be helpful if the limit on the dde-dock plugin was also 150%.

**Comment by talesam** [comment]
I agree with Bruno, it does not make much sense to have option to go beyond 100% and does not have a simple way to set up without having to open the configuration part.

**Comment by manateelazycat** [comment]
@bigbruno In control-center 150% just for when some of the software to play the sound is too small, the temporary adjustment of the volume used. Adjust to 150% later, the sound will break sound, greatly reducing the sound quality. So the Dock will not adjust to 150%, and keep rang between 0 and 100%.

@bigbruno @talesam Please understand, anyway, thanks for your suggetion! ;)
