### ISSUE TITLE
The dock doesn't appear on startup

### ISSUE THREAD

**Issue by KimHono** [linuxdeepin/dde-dock#276]
Hi,
Frequently, my dock doesn't appear on startup. Rebooting doesn't solve the problem.
When trying to launch `/usr/bin/dde-dock` manually, the message is:
`QApplication: invalid style override 'gtk' passed, ignoring it.
        Available styles: bb10dark, bb10bright, chameleon, dsemilight, dsemidark, dlight, ddark, cleanlooks, gtk2, cde, motif, plastique, Windows, Fusion
"dtkwidget" can not find qm files
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
2020-06-17, 07:25:01.217 [Info   ] [dguiapplicationhelper.cpp Dtk::Gui::DGuiApplicationHelper::setSingleInstance 919] Process is started: pid= 3309 arguments= ("/usr/bin/dde-dock")
2020-06-17, 07:25:01.217 [Debug  ] [                                                         0] set single instance failed!`

My configuration is:
Deepin v20
deepin-dock v5.1.0.11-1
deepin-dock = beautiful + smart hide
system = Linux x86_64
kernel = 5.7.2-arch1-1

**Comment by felixonmars** [comment]
You are setting Qt style override in some way. Please do not do that as it's always incompatible with DDE.

**Comment by KimHono** [comment]
I also noticed in another issue that installing `deepin-kwin` may fix the problem. So I tried that and it's true, but not alone : I also removed `deepin-mutter`, `deepin-wm` and `deepin-metacity`.
Apparently my system is now closer to the Debian config of Deepin.
