### ISSUE TITLE
Zombie icons on the dock

### ISSUE THREAD

**Issue by KimHono** [linuxdeepin/dde-dock#279]
Hi,
For strange reasons, when I launch some applications 2 icons are created on the dock:
- one really linked with the application windows
- the other just a zombie, with no function

So, 2 icons for 1 process, as we can see here:

![image](https://user-images.githubusercontent.com/26832779/85662959-d1e67300-b6b8-11ea-845b-9953364dadfc.png)

When I close an application, it's zombie icon is still there until shutdown.

My configuration is:
Deepin v20 Beta
deepin-dock v5.1.0.11-1
startdde v5.5.0.3-1
system = Linux x86_64
kernel = 5.7.5-arch1-1

**Comment by elisaado** [comment]
Same issue here.

**Comment by bgualda** [comment]
For me, the same issue.

![image](https://user-images.githubusercontent.com/853099/85934537-0d03c480-b8ba-11ea-868c-51771ab29636.png)


My configuration is:
lsb_release -a
LSB Version:	1.4
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
dde-dock 2.0


![image](https://user-images.githubusercontent.com/853099/85934589-032e9100-b8bb-11ea-92c7-e64f110756a7.png)

**Comment by franciscocpg** [comment]
Same for me.

```
LSB Version:	1.4
Distributor ID:	EndeavourOS
Description:	EndeavourOS Linux
Release:	rolling
Codename:	n/a
```

![image](https://user-images.githubusercontent.com/3680556/86769878-380eb680-c026-11ea-86b9-2a9ecffed080.png)

**Comment by Saduff** [comment]
https://github.com/linuxdeepin/developer-center/issues/1776

**Comment by KimHono** [comment]
@Saduff  Yes, same situation. Except my WM is Mutter, not kwin.

I recently upgraded to deepin-daemon v5.11.0.17-1, without improvment....

**Comment by brunogualda** [comment]
Hi gyus,

After upgrade this weekend, apparently problem was solved. 

First, I had removed lib libappindicator-gtk3, and problem like below solved:
![image](https://user-images.githubusercontent.com/853099/85934537-0d03c480-b8ba-11ea-868c-51771ab29636.png)

Commnad: `yaourt -R libappindicator-gtk3`

See:
![image](https://user-images.githubusercontent.com/67343206/87265718-e6d54b80-c499-11ea-8007-25c4102b4b49.png)


But when I opened any app, icons have still duplicate. 
So, when I upgrade the system this weekend, problem apparently was solved.
![image](https://user-images.githubusercontent.com/67343206/87265738-f3f23a80-c499-11ea-99d1-ab6a8bf0e444.png)

My system now:

``` 
yaourt -Q | egrep "deepin|dde"

community/deepin-account-faces 1.0.11-2 (deepin)
community/deepin-anything 5.0.1-3 (deepin)
community/deepin-anything-arch 5.0.1-91
community/deepin-api 5.3.0.3-1 (deepin)
community/deepin-boot-maker 5.4.8-1 (deepin-extra)
community/deepin-calculator 5.5.21-1 (deepin-extra)
community/deepin-calendar 5.7.0.3-1 (deepin)
community/deepin-clutter 1.26.2-3
community/deepin-cogl 1.22.5-3
community/deepin-control-center 5.2.0.19-1 (deepin)
community/deepin-daemon 5.11.0.17-1 (deepin)
community/deepin-desktop-base 2:2020.04.12.2-2 (deepin)
community/deepin-desktop-schemas 5.6.0.11-1 (deepin)
community/deepin-dock 5.1.0.11.20200622-1 (deepin)
community/deepin-file-manager 1:5.1.1.25-4 (deepin)
community/deepin-gtk-theme 2020.06.10-1 (deepin)
community/deepin-icon-theme 2020.06.30-1 (deepin)
community/deepin-image-viewer 5.6.3.2-2 (deepin)
community/deepin-launcher 5.2.0.13-1 (deepin)
community/deepin-menu 5.0.1-2 (deepin)
community/deepin-metacity 3.22.24-2
community/deepin-mutter 3.20.38-4
community/deepin-network-utils 5.1.0.1-1 (deepin)
community/deepin-picker 5.0.6-1 (deepin-extra)
community/deepin-polkit-agent 5.2.0.7-1 (deepin)
community/deepin-polkit-agent-ext-gnomekeyring 0.1.0-2 (deepin)
community/deepin-qt-dbus-factory 5.2.0.3-1
community/deepin-qt5integration 5.1.0.3-1 (deepin)
community/deepin-qt5platform-plugins 5.0.13-1 (deepin)
community/deepin-screensaver 5.0.3-1 (deepin)
community/deepin-session-shell 5.1.0.10-1 (deepin)
community/deepin-session-ui 5.2.0.11-1 (deepin)
community/deepin-shortcut-viewer 5.0.2-1 (deepin)
community/deepin-sound-theme 15.10.6-1 (deepin)
community/deepin-system-monitor 5.6.11-1 (deepin)
community/deepin-terminal 5.2.11-1 (deepin-extra)
community/deepin-turbo 0.0.3-2 (deepin)
community/deepin-wallpapers 1:1.7.7-2 (deepin)
community/deepin-wm 1.9.38-4
community/startdde 5.5.0.7-1 (deepin)
```




> For me, the same issue.
> 
> ![image](https://user-images.githubusercontent.com/853099/85934537-0d03c480-b8ba-11ea-868c-51771ab29636.png)
> 
> My configuration is:
> lsb_release -a
> LSB Version: 1.4
> Distributor ID: Arch
> Description: Arch Linux
> Release: rolling
> Codename: n/a
> dde-dock 2.0
> 
> ![image](https://user-images.githubusercontent.com/853099/85934589-032e9100-b8bb-11ea-92c7-e64f110756a7.png)

**Comment by KimHono** [comment]
Hi  @bgualda brunogualda,
Thanks for the idea !

When you right-click on a widget, can you still see any drill-down menus above your tray ?
For example above the network manager, or volume manager ?

**Comment by gardotd426** [comment]
This is a duplicate of linuxdeepin/developer-center#1776

**Comment by gardotd426** [comment]
Also, as mentioned in my original issue, when you close these programs the icons stay on the dock. You have to run `killall dde-session-daemon` which resets everything but it just starts all over again when you open more apps.

**Comment by KimHono** [comment]
I'm closing this issue : seems to be addressed in latest update of startdde or dde-daemon. I don't know which one of theses packages, but it's OK since mid-september.

**Comment by edomatic** [comment]
i still have this issue with deepin dock icons staying in dock , startdde 5.5.0.7-1 and dde-daemon 5.11.0.18-1
Deepin 20 community, kernel 5.4.50

**Comment by elisaado** [comment]
same here, I switched back to gnome because of this
