### ISSUE TITLE
编译不成功

### ISSUE THREAD

**Issue by leojplin** [linuxdeepin/dde-dock#288]
当我用 cmake 编译项目的时候会有以下的报错：
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/DtkCMake/DtkCMakeConfig.cmake:15 (message):
  "/usr/lib/x86_64-linux-gnu/libdtk-5.2.2/DCore/bin/deepin-os-release" is not
  exists.  Install "dtkcore-bin" first
Call Stack (most recent call first):
  frame/CMakeLists.txt:18 (find_package)

我也已经安装好了apt install libdtkcore-bin， 但是这个包里不包含编译所需的deepin-os-release 工具。 

请问有什么解决方法？

**Comment by leoxy520** [comment]
我手动编译deepin-os-release这个工具来解决这个问题了。但是不知道为什么手动编译deepin-os-release的时候，安装的目录是/usr/lib/libdtk-5.2.2/DCore/bin， 但是dde-dock编译时需要的路径是/usr/lib/x86_64-linux-gnu/libdtk-5.2.2/DCore/bin

**Comment by smartsmallking** [comment]
看下你的dtkcore的版本和任务栏的版本，
版本不匹配带来的问题较多，选择发布时间差不多的代码进行编译基本没问题
