### ISSUE TITLE
双屏显示时会随着鼠标左右移动

### ISSUE THREAD

**Issue by fengcs** [linuxdeepin/dde-dock#289]
刷屏显示，鼠标移动到dock位置，dock会在左右屏幕移动，鼠标移动到左边屏幕就在左边屏幕显示，鼠标移动到右侧就在右侧显示。这样动来动去不好，或者在屏幕显示的地方提供设置选项，或者应该跟随屏幕设置中的主屏幕。

**Comment by goto456** [comment]
> 刷屏显示，鼠标移动到dock位置，dock会在左右屏幕移动，鼠标移动到左边屏幕就在左边屏幕显示，鼠标移动到右侧就在右侧显示。这样动来动去不好，或者在屏幕显示的地方提供设置选项，或者应该跟随屏幕设置中的主屏幕。
------------
这样挺好的啊，挺实用的！下一个问题

**Comment by imic07** [comment]
提供配置项禁用好些。觉得没问题的应该是没有经常切换屏幕使用的经历。对开发人员来说，随时都在两个屏幕上切换，本来全屏的窗口，结果就跳来跳去，需要打开其他工具的时候，又必须先让他显示出来。太不方便了。建议深度系统开发人员使用deepinos 20 j进行软件开发，真实体验下，这样能是deepin进步的更快更好。

**Comment by xmuli** [comment]
重复反馈，新的回复请前往 #290 ，里面提供了原因和一个解决方案
