### ISSUE TITLE
dock 双屏时，dock会互相切换，如何固定在一屏

### ISSUE THREAD

**Issue by kkblock** [linuxdeepin/dde-dock#290]
连接外屏幕，当鼠标移动到另一个屏幕下边的时候，dock也会移动过去，如何关闭 或固定dock 在一个屏幕内

**Comment by imic07** [comment]
同问

**Comment by xmuli** [comment]
dock 更随系统鼠标移动，这是新设计，暂时无法固定（PS： 固定在一个屏幕，后面会加上）

**Comment by imic07** [comment]
@xmuli 希望尽快加上。目前我的使用情况，解决了这个问题，基本上就没有阻塞性大问题了

**Comment by xmuli** [comment]
该功能已经完成，还未对外开放，若是你想提前体验固定dock，可以安装 `dconf-editor` 然后，点击如下开关


![image](https://user-images.githubusercontent.com/33887845/93545921-3b161380-f994-11ea-8143-76589f9634ee.png)

**Comment by xmuli** [comment]
补充：dock 版本貌似要大于 dde-dock=5.3.0.20-1  才可以使用

**Comment by ms347397173** [comment]
大佬，没找到这个dock下的mainwidow呀，我的是20最新社区版。 @xmuli

**Comment by ms347397173** [comment]
dde-dock版本2.0,我擦

**Comment by xmuli** [comment]
> 大佬，没找到这个dock下的mainwidow呀，我的是20最新社区版。 @xmuli

If you want to try the beta version, then you can join the beta group (you can get the song on the bbs forum), then you have the beta source and update it to the very heart of the game.

**Comment by MangoPomelo** [comment]
gsettings set com.deepin.dde.dock.mainwindow only-show-primary true
检查一下拼写

widow和window
