### ISSUE TITLE
When multiple monitors are plugged taskbar shows randomly in one of them

### ISSUE THREAD

**Issue by vincenzocaselli** [linuxdeepin/dde-dock#293]
At work I have three monitors plugged in.
The taskbar keeps randomly changing monitor.
Is there a way to stuck to one of them?
Thank you

**Comment by luaVolk** [comment]
For me the taskbar changes monitor when I hover the mouse near the bottom of the monitor where it is not currently displayed. This happens even in "keep shown" mode.

**Comment by xmuli** [comment]
Repeat, see for solutions #290

**Comment by vincenzocaselli** [comment]
Ok @xmuli , I see.
But isn't the behaviour described by @luaVolk a bug? 
In "keep shown" mode (and without the proposed solution) shouldn't the taskbar be shown on all monitors?

**Comment by xmuli** [comment]
> In "keep shown" mode (and without the proposed solution) shouldn't the taskbar be shown on all monitors?

Currently dock is not supported for the time being. It is displayed on all monitors and will be supported later.

**Comment by xmuli** [comment]
In addition, the hold mode means that the dock will always be displayed (not hidden)
