### ISSUE TITLE
Wireless Icon (nor Control Center) doesn't show correct connected & available networks

### ISSUE THREAD

**Issue by vincenzocaselli** [linuxdeepin/dde-dock#295]
If I connect to a wireless network I can see the message showing "... connected", but:

1) the list of available network doesn't show that network (HUAWEI_P9lite in this case, always shown correctly in the past)

![image](https://user-images.githubusercontent.com/3648713/92299220-be754500-ef50-11ea-9e5b-cf19aaefcba3.png)

2) after connection to that network it shows connection to a wrong one

![image](https://user-images.githubusercontent.com/3648713/92299037-43f7f580-ef4f-11ea-904f-046e12ade33f.png)

is there any other way to manage the connected wireless networks?

**Comment by vincenzocaselli** [comment]
Even with latest big update of Oct. 22, 2020, there are still problems on this.
In the following image I am connected to wifi, but cannot see it
![image](https://user-images.githubusercontent.com/3648713/97052529-730b0a80-1581-11eb-9584-bfe08fb8a587.png)
Also I cannot switch to another wifi network

**Comment by smartsmallking** [comment]
it is a "long time before" question,I check it now .it OK
if you still run an error ,please reopen this
