### ISSUE TITLE
dde-dock进程占用cpu过高

### ISSUE THREAD

**Issue by wecli** [linuxdeepin/dde-dock#297]
![深度截图_dde-desktop_20200909215752](https://user-images.githubusercontent.com/42332005/92608392-e1ed1680-f2e7-11ea-9dd3-91757128b878.png)
系统：arch+dde桌面+deepin全家桶
描述：1、开机之后不登陆用户，长时间之后dde-dock进程占用cpu不会升高机器也不会发热；开机之后登录用户不论操作不操作dde-dock占用cpu会慢慢增加并维持这个水平，速度大概是在登陆用户后半个小时增加到20%~30%，自动隐藏dock之后再次唤出卡顿。

**Comment by xmuli** [comment]
看下场景， 来张截图， 我的显示正常， arch + dde

![image](https://user-images.githubusercontent.com/33887845/92584223-f28c9500-f2c5-11ea-8896-c83cf57c4ff4.png)

**Comment by xmuli** [comment]
版本呢？ 以及你的 cpu 版本呢？ 然后左上角是属于已知问题，后面会修复处理~，

或者
![image](https://user-images.githubusercontent.com/33887845/92670217-214a5000-f346-11ea-9264-52feb24a5af3.png)

**Comment by Scfy-Code** [comment]
cpu版本：i55200U
dde-dock版本:5.1.0.11.20200622-1（arch版本）

**Comment by xmuli** [comment]
我的是 i3 - 9 代，CPU: Intel Core i3-9100F @ 4x 4.2GHz [41.0°C]
感觉不算问题，因该是i5- 5 代 cpu 的问题，我看了好几台笔本都是正常的，属于正常，若是后面有其他和你很相同的问题，请再打开此问题，后面给优化一下

**Comment by hirale** [comment]
同样的问题且dde-dock版本也相同，重启进程就可恢复正常
CPU是 Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz

![image](https://user-images.githubusercontent.com/22028058/92996537-ac754280-f50c-11ea-898f-cd4f5ef88194.png)

**Comment by hirale** [comment]
@Scfy-Code 我把sougou输入法移除后，重启几次系统测试都是正常占用

**Comment by Scfy-Code** [comment]
> @Scfy-Code 我把sougou输入法移除后，重启几次系统测试都是正常占用

你打开firefox或者chromuim浏览器播放下视频，dde-dock进程占用的就会增加。十分钟左右会占用20%。我现在看视频都是看一会退出来把dde-dock干掉一次。

**Comment by hirale** [comment]
> > @Scfy-Code 我把sougou输入法移除后，重启几次系统测试都是正常占用
> 
> 你打开firefox或者chromuim浏览器播放下视频，dde-dock进程占用的就会增加。十分钟左右会占用20%。我现在看视频都是看一会退出来把dde-dock干掉一次。

按你的说法我测试了几次，问题复现

**Comment by xmuli** [comment]
我这会正在测试，看能否复现此问题（chrome 播放视频）；按照 [# 1763](https://github.com/linuxdeepin/developer-center/issues/1763) 所讲，此问题是在 deepin-dock 5.2.0.14-1 被修复

**Comment by taolin96** [comment]
我的cpu是i5 8代
![image](https://user-images.githubusercontent.com/7938311/95545510-8cc53180-0a5a-11eb-8008-ed40e1358d3d.png)

dde-dock 版本是 5.2.0.14-1
![image](https://user-images.githubusercontent.com/7938311/95545543-a797a600-0a5a-11eb-863c-f569b5e275e8.png)
一样有这个问题， CPU 占用持续在95%到100%之间

**Comment by sayoojsamuel** [comment]
@xmuli @taolin96 I had just noticed the excessive `stat(/etc/localtime)` in dde-dock ptrace. 

![image](https://user-images.githubusercontent.com/31436104/97430758-58e57980-193f-11eb-82e5-879d8bdf7187.png)

Also, here is the status of the calls when dde-dock takes up 30% of CPU
```
 I  ~  strace -c -f pgrep dde-dock     
9152
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 34.53    0.003613           7       481           read
 27.05    0.002830           6       470         1 openat
 19.35    0.002025           4       471           close
 13.00    0.001360           6       226           stat
  2.34    0.000245         122         2           getdents64
  1.14    0.000119           7        16           mprotect
  0.93    0.000097          24         4           munmap
  0.72    0.000075           1        59           mmap
  0.31    0.000032           1        19           fstat
  0.18    0.000019           4         4           brk
  0.13    0.000014          14         1           write
  0.08    0.000008           4         2           prlimit64
  0.06    0.000006           3         2           rt_sigaction
  0.05    0.000005           5         1           futex
  0.04    0.000004           4         1           getpid
  0.04    0.000004           2         2         1 arch_prctl
  0.03    0.000003           3         1           set_tid_address
  0.03    0.000003           3         1           set_robust_list
  0.02    0.000002           2         1           rt_sigprocmask
  0.00    0.000000           0         5           pread64
  0.00    0.000000           0         1         1 access
  0.00    0.000000           0         1           execve
------ ----------- ----------- --------- --------- ----------------
100.00    0.010464           5      1771         3 total
```

While the same status connecting 10 threads for the same process:
```
 I  !  ~  sudo strace -c -f -p 11501  
strace: Process 11501 attached with 10 threads
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 91.43    0.346369          67      5106           poll
  3.06    0.011608           7      1628       120 futex
  1.31    0.004955        1651         3           restart_syscall
  0.91    0.003460           3       983           write
  0.89    0.003378           5       619           writev
  0.86    0.003269           4       690           read
  0.64    0.002418           3       718       101 recvmsg
  0.34    0.001282           3       413           stat
  0.28    0.001051          11        95           sendmsg
  0.11    0.000415           4        99           statx
  0.09    0.000331           7        44           openat
  0.05    0.000205           4        44           close
  0.03    0.000112           3        33           lseek
------ ----------- ----------- --------- --------- ----------------
100.00    0.378853          36     10475       221 total
```

**Comment by sayoojsamuel** [comment]
The latest update in version `deepin-dock-5.2.0.19-1-x86_64` seems to have drastically reduced the number of `poll` syscall.    

The cpu utilization has now reduced and here is the new stats 
```
 I  ~  sudo strace -c -f -p (pgrep dde-dock)                                                            Wed 28 Oct 2020 12:47:45 PM UTC
strace: Process 14993 attached with 10 threads
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 69.37    0.001352         676         2           restart_syscall
  6.98    0.000136          11        12           stat
  6.31    0.000123           7        16           openat
  5.59    0.000109           3        33           read
  4.46    0.000087           2        36           statx
  4.10    0.000080          10         8           poll
  2.00    0.000039           2        16           close
  1.18    0.000023           1        12           lseek
  0.00    0.000000           0         1           write
  0.00    0.000000           0         1           recvmsg
------ ----------- ----------- --------- --------- ----------------
100.00    0.001949          14       137           total
```

**Comment by taolin96** [comment]
看似这个问题只发生在一些特定CPU family，在我的台式机上(CPU 是i7-4750S）就没有这个问题

**Comment by Cardellino** [comment]
Hello,
again and again I have to deepin-dock because the CPU runs at 100%.
Installed version -> deepin-dock 5.3.0.12
Client with Intel Core i7-4790K CPU ...
System Arch Linux ......
![Screen Capture_select-area_20201104084920](https://user-images.githubusercontent.com/73848158/98084585-52de2400-1e7c-11eb-832c-8c36d8d79540.png)

**Comment by Cardellino** [comment]
I wonder why dde-dock lets the processor work at 100% over and over again. When the process has been killed that's silence for a while. Then the same again .... Why?

**Comment by sayoojsamuel** [comment]
@Cardellino for the time being, you could make use of a bash script to temporarily handle this issue. 
Add the following script as a cron job with 3 minute interval.  

The script will kill the process if the CPU utilization crosses 20% mark.

```bash
#!/usr/bin/env bash
set -euo pipefail

ps -C dde-dock -o pid=,pcpu= |
    awk -vORS= --assign maxcpu=20.0 '$2>maxcpu {
        print "Killing dde-dock, pid:",$1," ";
        system("date");
        system("kill " $1);
        system("notify-send \"Respawning dock\"")
    }' >> ~/.dock-crash.log
```
Save this file as `dock-police`, perform a `chmod +x` and place it in `/usr/local/bin/`.   
Then you can add `*/3 * * * * /usr/local/bin/dock-police` to your cronlist.

**Comment by Cardellino** [comment]
Thank you sayoojsamuel that helps ....
After 3 minutes it is killed...:):)

**Comment by Scfy-Code** [comment]
现在还有一个现象，自从dde-dock升级到5.3.0.45之后的版本中。

**Comment by smartsmallking** [comment]
继续安排人员查看中

**Comment by dcb1** [comment]
这个问题最近有点严重。。。

**Comment by wzyfrank** [comment]
我也遇到了同样的问题，只要开着浏览器几个小时 就可以100%复现。 CPU:i7-6700HQ

**Comment by duanyao** [comment]
我也遇到过同样的问题。我用 Callgrind 对 dde-dock 进行了分析，发现消耗 CPU 的主要操作是 `QTimerInfoList::activateTimers()`，这个操作重复次数非常多，详见附件。

在我的机器上，重启 dde-dock 并没有效果，几分钟之内又会出现 CPU 占用高的问题。不过，待机-恢复操作效果可以久一点。

不过，升级到 deepin 20.2 之后（ dde-dock 5.4.7-1 ），这个问题似乎没有重现过，我正在继续观察。
[callgrind-dde-dock.zip](https://github.com/linuxdeepin/dde-dock/files/6301315/callgrind-dde-dock.zip)

**Comment by smartsmallking** [comment]
目前我这边还没有出现过以上状况，
如有新的发现，帮忙写一下复现步骤，感谢

**Comment by wecli** [comment]
> 目前我这边还没有出现过以上状况，
> 如有新的发现，帮忙写一下复现步骤，感谢

这个问题 在dde升级到20.1之后没有出现了。
