### ISSUE TITLE
无论玩什么游戏，无论是Wine的还是Linux原生的，无论是Vulkan的还是OpenGL的，只要全屏时按capslock/Shift其中任意一个，必定会弹出Dock，然后游戏就被弹出了，设置“一直隐藏”也没有用。

### ISSUE THREAD

**Issue by oldyangyagn** [linuxdeepin/dde-dock#299]
无论玩什么游戏，无论是Wine的还是Linux原生的，无论是Vulkan的还是OpenGL的，只要全屏时按capslock/Shift其中任意一个，必定会弹出Dock，然后游戏就被弹出了，设置“一直隐藏”也没有用。，怎么解决，我试了试ubuntu没这个问题，测试游戏是mc

**Comment by smartsmallking** [comment]
现在没有这个问题了呀，我开启了深度的文本编辑器，google浏览器，然后用F11全屏，按capslock/shift都没有出现任务栏呀
