### ISSUE TITLE
Recent change causes NET_WM_WINDOW_TYPE_DOCK not to be set

### ISSUE THREAD

**Issue by Drakulix** [linuxdeepin/dde-dock#3]
Since 3.0.4 (3.0.3 still works) the NET_WM_WINDOW_TYPE_DOCK flag is not set anymore on the X11 Dock Window. This no problem for Deepin's own Window Manager, but I am currently using the Deepin Stack in combination with i3 (which works very nicely otherwise). And i3 is relying on that flag.

Although this is probably not a very common use case, setting the right NET_WM_WINDOW_TYPE is good practice and I hope someone can help me with this issue.

**Comment by hualet** [comment]
@Drakulix Are you sure ? I just tested the 3.0.4 version, the _NET_WM_WINDOW_TYPE is set correctly to _NET_WM_WINDOW_TYPE_DOCK on deepin.

**Comment by Drakulix** [comment]
Okay I have verified myself, that the flag is set correctly with xprops. However may it be, that it is getting set later then in 3.0.3?

I have taken a look at the debug log of i3 and the check
(https://github.com/i3/i3/blob/next/src/manage.c#L217) is obviously failing. There is no other way this is not failing, because directly in the check and after it is a log message.

Do you have a hint maybe, where this flag should get set in dde-dock? Then I could try to debug it further on my own.

**Comment by hualet** [comment]
Here https://github.com/linuxdeepin/dde-dock/blob/master/dde-dock/src/mainwidget.cpp#L48, the property is set right on the main window initialization, so I don't think it will be a problem of time.

**Comment by Drakulix** [comment]
I just saw that reference to issue #249.

I can confirm, that 3a38d20 is indeed the commit, which introduced the error for me.
e7ceb38 is the last one that works.

**Comment by hualet** [comment]
@Drakulix I've submitted a commit, see #249 for more detail, please :smile:

**Comment by Drakulix** [comment]
Thanks. That fixed everything again.

Also thanks to whole deepin team for following standard protocols allowing other window managers to work. There are far to many desktop environments, that only work with their own complete software stack.

**Comment by hualet** [comment]
We'll try our best to follow the standard, but there'll still be many things not that perfect, we need your feedback and indeed grateful :+1:
