### ISSUE TITLE
a problem about archlinux dde

### ISSUE THREAD

**Issue by ghost** [linuxdeepin/dde-dock#30]
rt
![2016-12-18 08-59-29](https://cloud.githubusercontent.com/assets/16173759/21290783/ad7a00d2-c502-11e6-9b3c-07712a9b5aed.png)
![2016-12-18 08-59-48](https://cloud.githubusercontent.com/assets/16173759/21290784/b630a78a-c502-11e6-8a2c-e40d2fca6359.png)

**Comment by felixonmars** [comment]
We'll hopefully have a package tomorrow to address this...

**Comment by ouyangshi** [comment]
等上游他们修复咯

**Comment by felixonmars** [comment]
Do you still encounter this problem?

**Comment by ouyangshi** [comment]
yes,but now I am using gnome

**Comment by ceyhunnabiyev** [comment]
I am using latest Archlinux, Deepin DE, @felixonmars,  the problem still remained!!!

**Comment by felixonmars** [comment]
Just confirmed that it's an upstream problem, and should be fixed in deepin-menu.

**Comment by SalahAdDin** [comment]
Maybe this problem have to be with difference between `GTK Theme` and `Shell Theme`.

**Comment by smartsmallking** [comment]
This issue is too long, please reopen this issue if there is a similar issue
