### ISSUE TITLE
[Dock] Popup of Bluetooth / Wi-Fi List

### ISSUE THREAD

**Issue by foresee-io** [linuxdeepin/dde-dock#300]
Here is the picture for illustration.
<img width="573" alt="A83CBF0338572D3F09AE1F2F4C052247" src="https://user-images.githubusercontent.com/32860378/93704912-f385b800-fb4a-11ea-9bb0-fe914c1344fa.png">

**Comment by smartsmallking** [comment]
![image](https://user-images.githubusercontent.com/19384974/115200153-7ba25f00-a126-11eb-8ad8-f2f2a7cc9c44.png)

The Bluetooth module has recently undergone major changes, you can take a look
