### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by dacevedo12** [linuxdeepin/dde-dock#303]
![image](https://user-images.githubusercontent.com/29694570/94192961-4aee9580-fe75-11ea-92dc-4e9ca84c9f38.png)

![image](https://user-images.githubusercontent.com/29694570/94193025-69ed2780-fe75-11ea-9947-b60ab31d3c69.png)

**Comment by xmuli** [comment]
Be able to display the dock version number and your system version. In addition you can refer to [# 297](https://github.com/linuxdeepin/dde-dock/issues/297)

**Comment by dacevedo12** [comment]
dde-dock/unknown,now 5.2.0.14-1 amd64 [installed]
  deepin desktop-environment - dock module

DISTRIB_ID=Deepin
DISTRIB_RELEASE=20
DISTRIB_DESCRIPTION="Deepin 20"
DISTRIB_CODENAME=apricot
PRETTY_NAME="Deepin 20"
NAME="Deepin"
VERSION_ID="20"
VERSION="20"
ID=Deepin
HOME_URL="https://www.deepin.org/"
BUG_REPORT_URL="https://bbs.deepin.org/"

**Comment by smartsmallking** [comment]
see #297
