### ISSUE TITLE
Dock hover preview shows 4x4 of same window

### ISSUE THREAD

**Issue by nanoant** [linuxdeepin/dde-dock#304]
This is how the preview looks when I hover some of my running apps
![image](https://user-images.githubusercontent.com/103067/94349063-6d350e80-0041-11eb-8206-678325f90959.png)

Looks it may have something to do with display scaling `2.0` I use on my 4K display.

I am using deepin-dock 5.2.0.14-1 and deepin-wm 1.9.38-4 on Arch Linux.

Many thanks for looking into this issue, and providing such a great desktop environment.

**Comment by xmuli** [comment]
Thank you for your feedback.

**Comment by smartsmallking** [comment]
we check it again, now it works well on branch master.
if this problem happens again, reopen this issue.

**Comment by xmuli** [comment]
@nanoant @smartsmallking  

This is the design of the DTK (new version) (when the dee-dock is left and right, one side becomes right-angled); it is not a bug.

![image](https://user-images.githubusercontent.com/33887845/106995102-1ee70780-67b9-11eb-9b1e-150447a84520.png)
