### ISSUE TITLE
Shows in fullscreen

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/dde-dock#306]
HOW TO REPRODUCE:
- Launch a fullscreen application and use it for a few minutes.

RESULT:
- Eventually the dock will appear over the application screen.

SYSTEM:
- Deepin Dock 5.1.00.11.20200622-1
- Kwin 5.19.5
- Manjaro

**Comment by vesterlay** [comment]
Additionally pressing keys like ctrl, shift, alt, caps lock in games pulls the dock out. (You have to alt+tab to fix) 
When the dock is visible, it's unresponsive.

OS: Manjaro Deepin stable

**Comment by smartsmallking** [comment]
please use the lastest version to check again .I think this problem would be gone

**Comment by es20490446e** [comment]
I can't test: No longer using Deepin.

@vesterlay And you?

**Comment by vesterlay** [comment]
The issue is gone on my end

**Comment by PCPete68** [comment]
I know this is closed but Iam suffering the same problem 

deepin-dock 5.5.9.1-3
kwin 5.25.3-1
Arch
