### ISSUE TITLE
Dock does not stay fixed when using multiple monitors

### ISSUE THREAD

**Issue by ninjan3rd** [linuxdeepin/dde-dock#307]
If the cursor is moved to the bottom taskbar position of the monitor B the dock switches.The dock does not stay fixed on a single screen, but it jumps from monitor A to monitor B and vice versa. Issue is there on both "fashion" and "efficient" modes.

If this is the indented behavior it would be great to give an option to lock the dock on primary monitor.

Hats of the developer made the dock almost smooth in performance,animations and transitions.Great work.Cheers
Was a KDE user for a long time compared to the latte-dock which lags always..this is way smoother and fast ;)

**Comment by piyushthapa** [comment]
having same issue

**Comment by xmuli** [comment]
@ninjan3rd @piyushthapa 
Repeat, close, please refer. [290](https://github.com/linuxdeepin/dde-dock/issues/290#issuecomment-699744169)
