### ISSUE TITLE
Question : sending application to the dock where the config file?

### ISSUE THREAD

**Issue by hhaim** [linuxdeepin/dde-dock#308]
Where is the file is located? 

For Example for Spotify on the Desktop this is the file 
Were is the same for the doc?

~/Desktop$ more spotify_spotify.desktop 
[Desktop Entry]
Type=Application
Name=Spotify
GenericName=Music Player
Icon=/snap/spotify/42/usr/share/spotify/icons/spotify-linux-128.png
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/spotify_spotify.desktop /snap/bin/spotify --force-device-scale-factor=2  %U
Terminal=false
MimeType=x-scheme-handler/spotify;
Categories=Audio;Music;Player;AudioVideo;
StartupWMClass=spotify
X-Deepin-CreatedBy=com.deepin.dde.daemon.Launcher
X-Deepin-AppID=spotify_spotify

**Comment by smartsmallking** [comment]
![image](https://user-images.githubusercontent.com/19384974/106848772-8d11c880-66ec-11eb-926d-9edc3d51d5e2.png)
here!
