### ISSUE TITLE
Feature request: Net speed/stats dde-dock plugin

### ISSUE THREAD

**Issue by PlankCipher** [linuxdeepin/dde-dock#310]
First of all, I am really in love with this distro. I think, as for me, the only thing it needs to be complete is a net speed/stats dock plugin. Thanks again for this lovely piece of art and keep up the good work.

**Comment by xmuli** [comment]
This plug-in is already available, either in the gituhb or spark store. I forget the exact link, but I'm sure it's there. Once you've found it and it meets your expectations, you can close this issue.

**Comment by sayoojsamuel** [comment]
@PlankCipher here is a nice plugin by Sonichy: [CMDU_DDE_DOCK](https://github.com/sonichy/CMDU_DDE_DOCK)

Works like a charm.

**Comment by PlankCipher** [comment]
I actually tried this one and a couple of others but all of them don't update the status in the dock. I have to click on them to see the info in popup widget.

**Comment by xmuli** [comment]
@PlankCipher  You can try these two, [lfxSpeed](https://github.com/xmuli/lfxspeed) is a simple version; [lfxNet](https://github.com/xmuli/lfxnet) is a multifunctional version ( **lfxNet more recommended**)

![lfxMonitorNetHor](https://user-images.githubusercontent.com/33887845/106378171-6d715c00-63dd-11eb-8a82-c2a100015e76.gif)
![lfxMonitorNetVer](https://user-images.githubusercontent.com/33887845/106378174-6f3b1f80-63dd-11eb-88f3-cd10d97b223e.gif)

**Comment by PlankCipher** [comment]
@xmuli Excellent. IfxNet is exactly what I needed. Thanks a lot.
