### ISSUE TITLE
dock栏图标边界闪烁线条的问题

### ISSUE THREAD

**Issue by thefivestar** [linuxdeepin/dde-dock#312]
如图：![dde-dock_20201015211434](https://cdn.jsdelivr.net/gh/jinhaojun/ImgHosting/dde-dock_20201015211434.gif)

**Comment by thefivestar** [comment]
行吧，cdn也无法加载图片

**Comment by thefivestar** [comment]
直接上论坛链接，可以不[dock栏图标边界闪烁线条的问题](https://bbs.deepin.org/forum.php?mod=viewthread&tid=203902&extra=)

**Comment by smartsmallking** [comment]
论坛已回复
