### ISSUE TITLE
Dock disappear when unlock

### ISSUE THREAD

**Issue by JumperLuko** [linuxdeepin/dde-dock#313]
Sporadically i unlock my session, and dde-dock just looks invisible or not here.

I need to kill process and dock reappears.

I am using effect mode and dark mode, i test with eficient mode and fashion (the size of dock is the default).

**Comment by xmuli** [comment]
It would be better if there was a way to reliably reproduce the bug.

**Comment by smartsmallking** [comment]
This piece of content has been refactored, you can try to compile with the latest code
https://github.com/linuxdeepin/dde-dock/commit/1e3d90f62b9272b54c9267c68cb32aafbc526660
