### ISSUE TITLE
Bluetooth tray icon doesn't turn white when a device is connected.

### ISSUE THREAD

**Issue by abimagnus** [linuxdeepin/dde-dock#317]
Today i updated to the community edition 1003 with dde dock version 5.3.0.35, when a bluetooth device is connected the tray icon usually turns up to white however in new version it shows greyed out !
Was working fine with 1002 with dde dock version 5.2.0 i think.
Tried with different icon themes its the same !
![Screen Capture_select-area_20201022141841](https://user-images.githubusercontent.com/8939183/96848969-ae6ae380-1472-11eb-8a4e-184f1b568dbe.png)

**Comment by smartsmallking** [comment]
The good news is that we fixed this issue in the latest code
