### ISSUE TITLE
Deepin 20(1003) 编译安装显示插件和系统版本不兼容

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/dde-dock#318]
刚升级的 Deepin 20(1003)，Download Zip下载Dock源码，安装好依赖，编译，安装，显示插件和系统版本不兼容。

**Comment by xmuli** [comment]
若是更新有接口有变化， 那么使用的插件挂了是意料之中的。不明白为何要提一个 issues？

**Comment by sonichy** [comment]
不是使用插件挂了，是官方源码编译安装显示不兼容。

**Comment by xmuli** [comment]
嗯，是我一开始理解错了
