### ISSUE TITLE
Arch 版本的 Deepin 桌面更新後無法開啟 dde-dock，桌面右鍵選單也無法開啟

### ISSUE THREAD

**Issue by JulianLai** [linuxdeepin/dde-dock#32]
[user@user ~]$ dde-dock 
qt5ct: using qt5ct plugin
"dtkwidget" can not find qm files
load translate "/usr/share/dde-dock/translations/dde-dock_zh_TW"
2017-02-17, 23:02:41.515 [Debug  ] [main.cpp             main                                50] 

dde-dock startup
程式記憶體區段錯誤 (核心已傾印)

**Comment by ceyhunnabiyev** [comment]
I am using latest Archlinux Deepin DE, I have the same issue.. Please fix this!!!

**Comment by felixonmars** [comment]
Please try to downgrade qt5integration to 0.0.6-2 for now. @zccrs please look into this, thanks!

**Comment by zhtengw** [comment]
I updated all DDE packages in Gentoo, and have not met this error.

**Comment by felixonmars** [comment]
I don't think Gentoo has Qt 5.8. This error is not present on old Qt versions.

**Comment by zhtengw** [comment]
Yes @felixonmars , the latest Qt version in Gentoo is 5.7.1.

**Comment by ceyhunnabiyev** [comment]
Hi @felixonmars, after updating deepin-qt5integration  to 0.0.7-2,  it has  worked, but there is some issue too. I selected numix-circle icons from control-center , but dde-dock quick-access applications on the left has deepin-icon-theme. I killed dde-dock, but  it automatically re-launched and fixed this issue. After reboot, this issue occured again. That is strange!!!!

**Comment by sbwtw** [comment]
Is that problem still occurred @ceyhunnabiyev @JulianLai @zhtengw

**Comment by SalahAdDin** [comment]
I have this problem also.

**Comment by smartsmallking** [comment]
This problem should not exist now, if there is a segfault-like problem, reopen it！
