### ISSUE TITLE
Problem opening text files with Microsoft-CP1251 encoding from Libre Office.

### ISSUE THREAD

**Issue by btech-sewing** [linuxdeepin/dde-dock#320]
I am from Bulgaria and our coding is Microsoft-CP1251. When a computer from a Windows network transfers a text file written in Bulgarian, it is opened by Deepin's text editor correctly, but when I try to open the same file with the Libre office, what is written in Bulgarian is not readable. Libre office encoding is not recognized. How can this be fixed?

**Comment by smartsmallking** [comment]
Libre office is not maintained by deepin
you can fix this on Libre office
