### ISSUE TITLE
第三方插件宽度受到限制

### ISSUE THREAD

**Issue by q77190858** [linuxdeepin/dde-dock#321]
第三方的插件宽度在“上”“下”模式中被限制为26，第三方插件的高度在“左”“右”模式中被限制为26，有的时候确实需要显示超过一个图标的宽度和高度，但是无法显示完整，除了datetime这个官方插件例外，初步分析相关代码位于/dde-dock/frame/panel/mainpanelcontrol.cpp中1067行、1082行

![pic1](https://storage.deepin.org/forum/202010/24/230407w6rm4emmqqn34sen.jpg)

根据语义判断，datetime插件才使用他自己返回的sizehint，否则就返回默认托盘的大小

希望官方能修复这个问题，放开对第三方插件的宽度和高度的限制

[deepin论坛原贴附上](https://bbs.deepin.org/post/204354)

**Comment by xmuli** [comment]
我有看到那篇帖子，批评不是坏事，建议可以将帖子附上，看到批评才有改进

**Comment by xmuli** [comment]
dock 看起来比较忙碌（无奈），推荐可以自己撸袖子提交 pr， 会自动同步到内网有人审核~，并且给出建议

**Comment by q77190858** [comment]
> 我有看到那篇帖子，批评不是坏事，建议可以将帖子附上，看到批评才有改进

好的，我已经附上了

**Comment by q77190858** [comment]
> dock 看起来比较忙碌（无奈），推荐可以自己撸袖子提交 pr， 会自动同步到内网有人审核~，并且给出建议

好的，我改一改提交一下

**Comment by q77190858** [comment]
> dock 看起来比较忙碌（无奈），推荐可以自己撸袖子提交 pr， 会自动同步到内网有人审核~，并且给出建议

我拉取了一下最新的dde-dock代码，怎么变成go语言编写的了？？之前的文件完全找不到了啊

**Comment by q77190858** [comment]
尝试修改了一下老版的dde-dock，改完make install以后重启dde-dock，插件还是被限制宽度了，求指导啊，我把涉及到datetime字符串判断的4个地方都改了，还是不行，感觉有点复杂

**Comment by xmuli** [comment]
我现在在搞其它的事情, 然后这个结束了, 我去学习 dock 的插件机制,  到时候帮你修改一下吧.(等待时间会比较长)

**Comment by xmuli** [comment]
> 我拉取了一下最新的dde-dock代码，怎么变成go语言编写的了？？之前的文件完全找不到了啊

前两天操作失误,  填错了推送地址, 已经回恢复

**Comment by q77190858** [comment]
试着修改了一下，搞了个pr你们看看吧

**Comment by xmuli** [comment]
嗯, 内网提交已经看到了 pr, 提交规范需要修改一下

**Comment by xmuli** [comment]
暂时关闭, 最新参见上面 pr 链接
