### ISSUE TITLE
after (2020.11.13) update Dock is missing

### ISSUE THREAD

**Issue by tanvir-kx** [linuxdeepin/dde-dock#328]
After DEEPIN SYSTEM UPDATES (2020.11.13) dock is gone. 

![image](https://user-images.githubusercontent.com/68131844/99157939-a6136a80-26f7-11eb-88b5-e726eaa6ce91.png)

**Comment by ninjan3rd** [comment]
same for me..only way to show is to enter command dde-dock from terminal ! An update should fix problem not to create new ones..lol

**Comment by serial02** [comment]
All Distros that have DDE-dock or Deepin-Dock have several Bugs. When will there be a definitive correction and update for these problems presented by countless users?

**Comment by xmuli** [comment]
Already fixed, see https://bbs.deepin.org/post/206032

**Comment by serial02** [comment]
Será?

Outras distros continuam com os mesmos problemas.

https://github.com/linuxdeepin/dde-dock/issues/325

**Comment by smartsmallking** [comment]
use the version 5.4.2 to try again
it works well

**Comment by smartsmallking** [comment]
There are a lot of problems in this area. Recently, I have refactored a bit. Currently, I haven’t encountered any major problems.


https://github.com/linuxdeepin/dde-dock/commit/1e3d90f62b9272b54c9267c68cb32aafbc526660
