### ISSUE TITLE
dock栏的多任务视图无法打开

### ISSUE THREAD

**Issue by wecli** [linuxdeepin/dde-dock#329]
系统：arch+dde
deepin-dock版本：5.3.0.17
操作：将多任务视图显示在dock中，点击多任务视图图标。
预期结果：进入多任务视图页面，可以创建删除移动工作区，可以将窗口在工作区中移动。
实际结果：该图标点击无反映，不能进入多任务视图页面。
tip：使用deepin-wm作为窗口管理器时可以点击该按钮，切换至kwin之后无法使用。

**Comment by smartsmallking** [comment]
这是个老问题了，你需要使用deepin-kwin和dde-kwin这两个包才行

**Comment by scfx** [comment]
> 这是个老问题了，你需要使用deepin-kwin和dde-kwin这两个包才行
大佬，arch上任务视图是dde和kwin的兼容性问题。arch中deepin-kwin对应的是dde-kwin。arch中没有deepin-kwin对应的包。

**Comment by wecli** [comment]
> 这是个老问题了，你需要使用deepin-kwin和dde-kwin这两个包才行
大佬，我使用的是arch系统，只能安装dde-kwin。没法安装deepin-kwin包，使用还是kde的kwin

**Comment by wecli** [comment]
最新的arch该问题已得到解决
