### ISSUE TITLE
[Enhancement] Independent Theme Switch 獨立主題開關 独立皮肤开关

### ISSUE THREAD

**Issue by XiaoPanPanKevinPan** [linuxdeepin/dde-dock#330]
I want to use the light theme of the system cuz some of the apps don't support dark theme perfectly.
However, I think the dark theme of the dock is way more beautiful than the light theme of it.
So, I hope there will be an independent switch which can change only the theme of the dock and which should works like those buttons in the calendar app, the picture app, the control centre app, the music app, the movie app and so on.

因為有許多的應用程式並不支持深色主題，所以我想要把系統主題改成淺色。
但！是！我覺得深色主題中的工作列遠比淺色中的還要美觀許多，
所以我希望有一個開關，可以獨立地切換工作列主題，就像是日曆、圖片、控制中心、音樂、影片等等的應用程式一樣。

因为有许多的应用程式并不能很好地支持深色皮肤，故我希望能将系统皮肤改变为浅色。
然而，浅色皮肤的任务栏实在是比不上深色的，
因而我期望有一个开关，可以分开地切换任务栏主题，如同日历、图片、控制中心、音乐、影片等等应用程式一般。

**Comment by smartsmallking** [comment]
任务栏设计的就是跟随系统主题自动变换，暂时没有修改需求的必要，如果你需要的话，可以自己fork后进行修改，只需要在main函数中加一行即可
DGuiApplicationHelper::instance()->setPaletteType(DGuiApplicationHelper::LightType);
