### ISSUE TITLE
Enter wrong password at login

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/dde-dock#331]
Hello Deepin Team / UOS V20 1003

Upon entering the rest screen and perhaps entering the wrong password for a number of reasons, the screen simply locks up and does not return with the information that the password is wrong. The situation remains for a long time without being able to enter the correct password again.

**Could the login screen just inform you that the password is wrong and simply let the user enter the correct password?**

Below is a mp4 image of the login screen problem showing that I am using Deepin V20, so as not to generate absurd questions.

Note: Temporary solution is to enter TTy2 mode and enter "name and password" to unlock this situation so that we can then return to the login screen again.

https://www.youtube.com/watch?v=6hP8pcrt5Gg&feature=youtu.be

![Captura de Tela_dde-control-center_20201122140852](https://user-images.githubusercontent.com/32621790/99910860-3725ab00-2ccf-11eb-80be-976027f37025.png)

**Comment by smartsmallking** [comment]
when this happens again,give me the version of 'deepin-authenticate'

apt policy deepin-authenticate

but i think it won`t happen again
