### ISSUE TITLE
使用笔记本外接显示器时，如果把显示器断开再接入，任务栏的大小会变成最小的状态。

### ISSUE THREAD

**Issue by deltacatxx** [linuxdeepin/dde-dock#333]
多屏显示模式使用的是自定义—拆分模式，设置外界显示器为主屏并关闭笔记本的显示器。

**Comment by justforlxz** [comment]
能否提供截图或者视频?

**Comment by deltacatxx** [comment]
可能要到后天才能发给你，因为我现在在家。没有外接显示器------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;流年匆忙&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月18日(星期五) 晚上8:41
收件人:&nbsp;&quot;linuxdeepin/dde-dock&quot;<dde-dock@noreply.github.com&gt;;
抄送:&nbsp;&quot;deltacatxx&quot;<deltacatxx@foxmail.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [linuxdeepin/dde-dock] 使用笔记本外接显示器时，如果把显示器断开再接入，任务栏的大小会变成最小的状态。 (#333)

**Comment by deltacatxx** [comment]
> 能否提供截图或者视频?

[视频.zip](https://github.com/linuxdeepin/dde-dock/files/5721932/default.zip)

**Comment by justforlxz** [comment]
感谢。已安排开发人员进行检查。

**Comment by smartsmallking** [comment]
我用目前的版本试了下，没有出现这个问题了，你确认下，没有问题就可以关闭此issue了-_-
