### ISSUE TITLE
Clock on dock cannot be fully seen

### ISSUE THREAD

**Issue by ben321** [linuxdeepin/dde-dock#335]
Hi developers, great work on the Linux distribution,  this is the first Linux distribution that I like so far and I hope to continue to using it in the future and see more great works on it.  Here is an issue I noticed after updating to the latest version, I believe the previous version does not have this issue:  
 I noticed the clock is on the dock is not fully visible, please see attached image.
Notice the time is 10:20 AM, but you are not able to see the 1 and M properly.
![image](https://user-images.githubusercontent.com/6061784/101663767-52e7bb80-3a08-11eb-997b-2f14fcc5faf4.png)

**Comment by smartsmallking** [comment]
You can use the code on branch "maintain/5.2" now and it works well.
branch "uos" works well too，If you still have problems，reopen this issue and give me the commit id，thank you!

**Comment by khumnath** [comment]
Dde-dock 5.4.10-1 here problem unsolved yet
![20210615_210435](https://user-images.githubusercontent.com/50103558/122049591-912dbf80-ce1d-11eb-8c10-d21bdaf67f3a.jpg)
