### ISSUE TITLE
Where does Dock save docked apps?

### ISSUE THREAD

**Issue by ahmadidev** [linuxdeepin/dde-dock#339]
I'm curious to know the place of docked apps in Deepin Dock. Where the docked apps list is saved?
How can I find related code in its source code?

**Comment by zyiLoong** [comment]
`gsettings get com.deepin.dde.dock docked-apps`

maybe

**Comment by smartsmallking** [comment]
> `gsettings get com.deepin.dde.dock docked-apps`
> 
> maybe

YES

**Comment by smartsmallking** [comment]
as @zyiLoong mentioned
