### ISSUE TITLE
Blur effect gets missing after some actions

### ISSUE THREAD

**Issue by veyselerden** [linuxdeepin/dde-dock#341]
![image](https://user-images.githubusercontent.com/12845347/103445344-e1580180-4c83-11eb-8021-f097258606b0.png)

As you can see in the image if I ever set it to hide, it comes back without the blur effect. Same applies to changing the location of the dock. I think it needs to re apply the blur effect after actions.

**Comment by smartsmallking** [comment]
arch or deepin?

**Comment by veyselerden** [comment]
> arch or deepin?

Deepin.

**Comment by AcidRain9** [comment]
Yeah it happens with me as well

Steps to reproduce:
1. Set the dock to Fashion mode(In my case it only happens in Fashion Mode)
2. Choose Status > Auto Hide
3. Open an application and hover the mouse over the dock a few times the blur will disappear

**Comment by smartsmallking** [comment]
The blur effect is provided by the window manager。
https://github.com/linuxdeepin/deepin-kwin
