### ISSUE TITLE
dde-dock is abnormal under two screens

### ISSUE THREAD

**Issue by whg517** [linuxdeepin/dde-dock#348]
引用原贴: [[任务栏] 双屏状态下任务链异常](https://bbs.deepin.org/zh/post/211525)

https://user-images.githubusercontent.com/21030747/105707477-f86dd480-5f4d-11eb-8cbd-b7f1b43245da.mp4

如果需要，我可以提供更详细信息。

**Comment by smartsmallking** [comment]
为了防止任务栏在双屏之间频繁的切换位置，任务栏显示在当前屏幕时，如果在另外一张屏幕被唤起，这个唤醒时长是2秒，同时你也可以设置任务栏仅显示在主屏，这样就不会在另外一张屏幕被唤醒，如果你的版本比较新，可以用以下命令开启此功能gsettings set com.deepin.dde.dock.mainwindow  only-show-primary true（关闭只需要改为false）
确认解决了你的问题，请关闭这个issue，谢谢
