### ISSUE TITLE
Menu in panel like mac os

### ISSUE THREAD

**Issue by skypce** [linuxdeepin/dde-dock#35]
Hi again , will be great if you have a top bar with menu in it , like the global menu of unity. I can see that you are matching linux with windows 7 interface.  I like a lot global menu in top bar. thank you

**Comment by dimitrov-adrian** [comment]
+1

**Comment by ilfarme** [comment]
+1

**Comment by ilfarme** [comment]
That would be great solution for placing system tray and windows headings.

**Comment by smartsmallking** [comment]
Good idea, but what about the tray icon? Any good suggestions?

**Comment by smartsmallking** [comment]
This is a big project, but according to our current design, it is obvious that we do not intend to do this, thank you for your suggestions
