### ISSUE TITLE
热拔插hdmi线后时间显示异常

### ISSUE THREAD

**Issue by Wesly186** [linuxdeepin/dde-dock#352]
**笔记本屏幕分辨率1920\*1080，hdmi屏幕分辨率为2560\*1080**
![image](https://user-images.githubusercontent.com/16346644/107133717-1c55f080-6926-11eb-832d-6e9d9fd006c8.png)

**拔掉hdmi线后时间显示异常，鼠标悬浮到时间控件后显示恢复正常**
![image](https://user-images.githubusercontent.com/16346644/107133747-722a9880-6926-11eb-9fd0-070741af9f67.png)

**Comment by smartsmallking** [comment]
升级到最新版本就没这个问题了，内部开发已反馈修复过了

**Comment by Wesly186** [comment]
@smartsmallking 问题未解决
![image](https://user-images.githubusercontent.com/16346644/109130832-216fc800-778d-11eb-9f9d-0f1d4fb14aff.png)
系统已更新最新版本

**Comment by Wesly186** [comment]
@manateelazycat
