### ISSUE TITLE
未充电情况下电池电量提示显示不正确

### ISSUE THREAD

**Issue by Wesly186** [linuxdeepin/dde-dock#353]
**笔记本在未充电情况下，电池电量提示不正确，永远是已充满，电池图标里绿色的显示的是正确的**
![image](https://user-images.githubusercontent.com/16346644/107133773-b027bc80-6926-11eb-9537-f628342d41d1.png)

**电池信息如下**
![image](https://user-images.githubusercontent.com/16346644/107133794-e6653c00-6926-11eb-86d6-22e55086390d.png)

**Comment by smartsmallking** [comment]
出现这个情况的时候，运行以下命令
upower -i `upower -e | grep 'BAT'`
把输出拿出来看一下，这里感觉应该是内核的问题

**Comment by Wesly186** [comment]
@smartsmallking 实际电量96%，显示已充满，在电源中关闭这个选项，可以正确显示96%

![image](https://user-images.githubusercontent.com/16346644/108296780-1dfc9f80-71d5-11eb-8396-a916b3d0337f.png)

```
weixiang@weixiang-pc:~$ upower -i `upower -e | grep 'BAT'`
  native-path:          BAT0
  vendor:               Hewlett-Packard
  model:                Primary
  serial:               36251 03/05/2020
  power supply:         yes
  updated:              2021年02月18日 星期四 10时32分53秒 (27 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    energy:              37.6299 Wh
    energy-empty:        0 Wh
    energy-full:         39.0275 Wh
    energy-full-design:  39.0275 Wh
    energy-rate:         6.93609 W
    voltage:             12.622 V
    time to empty:       5.4 hours
    percentage:          96%
    capacity:            100%
    technology:          lithium-ion
    icon-name:          'battery-full-symbolic'
  History (charge):
    1613615573  96.000  discharging
  History (rate):
    1613615573  6.936   discharging
```

**Comment by smartsmallking** [comment]
受限于不同电池，有的电池充到一定程度(可能老化，可能是厂家的设置)就不会再充电了，这里的
state:               discharging
可以说明，所以我们判断了这种情况下就显示已充满，控制中心的这个选项是为了有的人会觉得这样提示不好，所以做了这个开关，如果你需要显示实际电量的百分比，不要打开控制中心的选项即可，只会显示电量%1或正在充电%1

**Comment by Wesly186** [comment]
@smartsmallking 
`state:  fully-charged`
这种情况是已充满
`state:  discharging`
这种情况是未插电源，处于放电状态，难道不应该取值percentage: 96%吗？为什么显示已充满？
