### ISSUE TITLE
Wireless icon problem

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/dde-dock#356]
When there is no connection, the wireless icon on the dock does not display any notification about the problem.

![Captura de Tela_select-area_20201129090353](https://user-images.githubusercontent.com/45263160/100688832-f9292680-3361-11eb-9224-863271b7745f.png)

I suggest that the exclamation point to be displayed on the wireless icon, be large and yellow - to be highlighted (as shown in the image below):

![Wireless-icon svg 2020_11_30_21_53_42 0](https://user-images.githubusercontent.com/45263160/100688843-ffb79e00-3361-11eb-827d-4c0b474defcf.png)

dde-dock 5.3.0.54-1
deepin 20 (1003 Update 1) / OsBuild=11031.106

**Comment by smartsmallking** [comment]
According to what is involved, this icon appears when you are connected but unable to access the Internet. Your situation is a bug, can you provide some steps to facilitate the recurrence of this problem?

**Comment by lxwndr** [comment]
> According to what is involved, this icon appears when you are connected but unable to access the Internet. Your situation is a bug, can you provide some steps to facilitate the recurrence of this problem?

Are you a developer of deepin?

Currently, the problem seems to be solved. But I believe, that the exclamation point should have a yellow color; to get more attention.

**Comment by smartsmallking** [comment]
Yes, I am a developer of deepin!

When the problem occurs, run the following command,
gsettings get com.deepin.dde.network-utils network-checker-urls
Check the output URL, try to use the ping command to test one by one, and see the results. In theory, if the network is connected but cannot be accessed, the ping result should fail.

**Comment by lxwndr** [comment]
I opened a new request, intended for suggestion; because the initial problem has been solved.
