### ISSUE TITLE
[Feature Request] Add glow effect to a wastebasket when removing a file through drag-n-drop

### ISSUE THREAD

**Issue by vesterlay** [linuxdeepin/dde-dock#363]
I would add a small glow effect on the wastebasket to indicate when you can release your mouse.

**Comment by AcidRain9** [comment]
Yeah that will be nice

**Comment by smartsmallking** [comment]
Good idea, I will feed it back to the product department

**Comment by 0yanghongwei** [comment]
@vesterlay We plan to add your suggestion in a later version. Thank you for your suggestion.

**Comment by vesterlay** [comment]
> @vesterlay We plan to add your suggestion in a later version. Thank you for your suggestion.

Thanks man for taking my ideas into consideration. I hope this effect will nicely integrate into the design of this system :)
