### ISSUE TITLE
App Indicator becomes black and hard to see

### ISSUE THREAD

**Issue by AcidRain9** [linuxdeepin/dde-dock#365]
Some applications' inactive indicator becomes black and it gets very hard to see it

![dock](https://user-images.githubusercontent.com/26188786/113139804-0509f400-9241-11eb-90e0-ca8322624c1c.jpg)

**Comment by smartsmallking** [comment]
Can you provide a complete reproduction step, thank you very much！

**Comment by simeithander** [comment]
i have a same issue, all the program running in secondary its the indicator in dark color

![Screenshot from 2021-05-05 18-30-35](https://user-images.githubusercontent.com/823040/117212066-35105e00-add0-11eb-9084-60cbb33e93f1.png)

all programs in the dock are running but only the first one in the stack is highlighted, the rest are very complicated to know if they are running or not

**Comment by 0yanghongwei** [comment]
It has been fixed.

**Comment by smartsmallking** [comment]
dba52c6549d1063bd5cdd51e6426a0e279fb8338

It has been fixed!
