### ISSUE TITLE
你们dock上的托盘不能换行啊

### ISSUE THREAD

**Issue by chen244** [linuxdeepin/dde-dock#366]
![截图_20210404221347](https://user-images.githubusercontent.com/60290287/113511606-29dccf00-9593-11eb-9b5a-cccde61583c2.png)
你们看啦。。。又是你们qt样式的问题吗？

**Comment by xmuli** [comment]
？？？

目测插件就开发者没有加换行符 “\n” 

![image](https://user-images.githubusercontent.com/33887845/113645063-bf25b380-96b8-11eb-8600-86001b06b59d.png)

**Comment by chen244** [comment]
不是，是应用的托盘不能换行，实际上是有换行符的。。
话说老哥离职了？

**Comment by chen244** [comment]
> ？？？
> 
> 目测插件就开发者没有加换行符 “\n” 
> 
> ![image](https://user-images.githubusercontent.com/33887845/113645063-bf25b380-96b8-11eb-8600-86001b06b59d.png)
> 

不是，是应用的托盘不能换行，实际上是有换行符的。。
话说老哥离职了？

**Comment by chen244** [comment]
> ？？？
> 
> 目测插件就开发者没有加换行符 “\n” 
> 
> ![image](https://user-images.githubusercontent.com/33887845/113645063-bf25b380-96b8-11eb-8600-86001b06b59d.png)
> 

海天鹰先生在托盘上加了换行符，在其他发行版都正常换行，唯独deepin换不了行，除此外其他应用，qt的托盘在dde-dock上都换不了行

**Comment by xmuli** [comment]
应用程序看起来是，需要仔细看下是缺陷还是设计如此。多谢反馈

**Comment by chen244** [comment]
> 应用程序看起来是，需要仔细看下是缺陷还是设计如此。多谢反馈

老哥还负责这个项目吗？听说老哥离职了。。现在在哪里啊

**Comment by sonichy** [comment]
托盘提示不能处理换行我早就发现了，下面的截图是插件，是可以换行的。

**Comment by 0yanghongwei** [comment]
@sonichy 你好，此问题已修复

**Comment by chen244** [comment]
> @sonichy 你好，此问题已修复


我尝试了你们的内测的镜像，并没有，是还没推吗？

**Comment by chen244** [comment]
![截图_20210525132149](https://user-images.githubusercontent.com/60290287/119443490-46f47980-bd5c-11eb-87a2-e425ac14b41b.png)

**Comment by 0yanghongwei** [comment]
@chen244 镜像应该是还没有集进去，不过这里的代码已经修改

**Comment by smartsmallking** [comment]
已经修复d941a19a44156f3c8ad8dd020b49daa8d452ddf1

**Comment by smartsmallking** [comment]
已经修复
d941a19a44156f3c8ad8dd020b49daa8d452ddf1
