### ISSUE TITLE
20.2第三方dock插件右键菜单消失，不在列表中，安装后无法加载

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/dde-dock#368]
升级 Deepin 20.2 后第三方 Dock 插件问题：
1.第三方 Dock 插件右键菜单消失。
2.第三方 Dock 插件不在插件列表中。
3.第三方 Dock 插件升级前有的可以显示，升级后安装的无法加载。
4.显示桌面插件无法从插件列表取消显示，其右键移除驻留也无效。

~/.cache/deepin/dde-dock/dde-dock.log 有报错：
"DockPlugin" plugin api version not matched! expect versions: ("1.1.1", "1.2", "1.2.1", "1.2.2", "1.2.3") , got version: "" , the plugin file is: "/usr/lib/dde-dock/plugins/libdatetime1.so"
"DockPlugin" load plugin failed!!!

**Comment by smartsmallking** [comment]
可否提供一下升级后的dde-dock的版本，

ps:现在master分支最新代码应该不会有这些问题了吧

**Comment by sonichy** [comment]
dde-dock/未知,now 5.4.7-1 amd64

**Comment by smartsmallking** [comment]
抱歉这么晚才回复

1.这个第三方插件能提供一个动态库，方便我验证下吗
2.同上
3.升级后安装的无法卸载是什么意思，是通过什么方式卸载的，可否有详细的卸载过程
4.这个问题目前正在修复中，如果感觉影响使用。可以先回退任务栏的版本

**Comment by sonichy** [comment]
1，2：右键消失，无法加载
我改了一个时间插件，做了1个网速和1个天气。
https://github.com/sonichy/dde-dock-datetime
https://github.com/sonichy/CMDU_DDE_DOCK
https://github.com/sonichy/WEATHER_DDE_DOCK

3.加载 不是 卸载，和2是同一个问题。

4.运行 dbus-monitor interface=com.deepin.dde.daemon.Dock 或者 dbus-send --session --print-reply --dest=com.deepin.dde.daemon.Dock /com/deepin/dde/daemon/Dock com.deepin.dde.daemon.Dock.GetPluginSettings 修好了，奇怪。

**Comment by sonichy** [comment]
好像已经修复了，我记得没更新啊？
