### ISSUE TITLE
Cannot get the same feel as Deepin15

### ISSUE THREAD

**Issue by G3NSVRV** [linuxdeepin/dde-dock#369]
Can you folks bring back the old Fashion Mode dock behaviour? the new one looks terrible extended in the desktop:
## Old (good)
![image](https://user-images.githubusercontent.com/11720535/114109477-59e1e600-98a3-11eb-8a96-feeedeae4775.png)

## New (bad)
![image](https://user-images.githubusercontent.com/11720535/114109528-741bc400-98a3-11eb-8a1f-170e44827c56.png)

**Comment by smartsmallking** [comment]
![image](https://user-images.githubusercontent.com/19384974/115186322-10e82800-a114-11eb-86bd-c8654be87352.png)
Maybe you can set the system theme to black，it looks nice!

**Comment by G3NSVRV** [comment]
why this was closed?
