### ISSUE TITLE
窗口预览画面显示异常

### ISSUE THREAD

**Issue by zty199** [linuxdeepin/dde-dock#370]
论坛有人反馈说窗口预览画面有问题，像是4张图片拼接显示的样子，类似于平铺......
我这里原本显示正常，今天发现可能和 QT 的显示缩放有关系......

经过简单测试，在控制中心将系统缩放设置为 1.0，然后以 env QT_SCALE_FACTOR=1.25 dde-dock 这样的方式运行 dde-dock 时会有这种情况，应该与显卡驱动无关。同样的问题也能以相同的方式复现在 deepin-movie 的进度条预览画面上。

猜是不是 QPainter 绘图处理有点问题，不知道有没有办法正确处理应用显示缩放的问题？

![截图_dde-desktop_20210412015706](https://user-images.githubusercontent.com/46324746/114315661-747dbe80-9b32-11eb-934e-fea94ea81fe4.png)

![截图_deepin-movie_20210412015730](https://user-images.githubusercontent.com/46324746/114315667-78114580-9b32-11eb-9ca3-1b8067a3d934.png)

**Comment by smartsmallking** [comment]
commit 3a630fe82f437d3523d2f092a11f2c21963e8259
这里最近修复了
