### ISSUE TITLE
显示桌面无法移除驻留

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/dde-dock#372]
显示桌面移除驻留无反应。
Dock右键 - 插件，去勾显示桌面，无反应。

**Comment by smartsmallking** [comment]
我使用master分支编译的代码没有这个问题，可否说明一下你使用的代码是什么时候提交的，能附图或视频的话会更方便我们这边定位

**Comment by sonichy** [comment]
20.2 啊啊啊

**Comment by smartsmallking** [comment]
取消插件的勾选实际上是通过调用dde-session-daemon提供的一个DBus方法，MergePluginSettings，使用
dbus-monitor  interface=com.deepin.dde.daemon.Dock监听对应方法的调用情况，应该可以看到如下信息，

![image](https://user-images.githubusercontent.com/19384974/115322402-96251880-a1b8-11eb-8065-75ef07ad3d72.png)

在取消勾选后，在终端中运行dbus-send --session --print-reply --dest=com.deepin.dde.daemon.Dock /com/deepin/dde/daemon/Dock com.deepin.dde.daemon.Dock.GetPluginSettings查看一下当前配置情况，里面的show_desktop的enable应该是false的，如果还是true可能是dde-session-daemon这个进程出现问题了，需要说明一下你使用的dde-daemon的版本（apt policy dde-daemon查看版本），可以附图给我

**Comment by sonichy** [comment]
运行 dbus-monitor interface=com.deepin.dde.daemon.Dock 还是 dbus-send --session --print-reply --dest=com.deepin.dde.daemon.Dock /com/deepin/dde/daemon/Dock com.deepin.dde.daemon.Dock.GetPluginSettings 后，恢复正常了！
