### ISSUE TITLE
屏幕缩放1.x倍后dock预览窗口×4

### ISSUE THREAD

**Issue by forliuyifei** [linuxdeepin/dde-dock#373]
![image](https://user-images.githubusercontent.com/53306807/116020332-a76a9b00-a678-11eb-8719-c4a50c55599b.png)

**Comment by smartsmallking** [comment]
3a630fe82f437d3523d2f092a11f2c21963e8259
已经修复了，您可以更新后再看下

**Comment by forliuyifei** [comment]
> [3a630fe](https://github.com/linuxdeepin/dde-dock/commit/3a630fe82f437d3523d2f092a11f2c21963e8259)
> 已经修复了，您可以更新后再看下

请问这个“更新”指的是什么？等系统更新吗？
