### ISSUE TITLE
取消右下角显示桌面按钮

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/dde-dock#374]
很容易误触，引起桌面闪动。

**Comment by smartsmallking** [comment]
时尚模式下没有这个区域，另外我不记得是不是有这样一个配置项，可以让这个区域显示或隐藏了，要等节后确认一下

**Comment by 0yanghongwei** [comment]
@sonichy 设计如此，在高效模式下，该功能是无法关闭的

**Comment by smartsmallking** [comment]
目前暂时没有这个配置，可以使用时尚模式
