### ISSUE TITLE
浅色模式桌面黑色壁纸时间看不清

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/dde-dock#375]
我晚上习惯把桌面换成黑色背景护眼，浅色模式时间是黑色的，只能调成深色模式时间才能白色。
![alt](https://ae01.alicdn.com/kf/U05b7e2c3bb584a85a1b98bfaa5f9b31bo.jpg)

**Comment by smartsmallking** [comment]
OK，节后会复查一下

**Comment by 0yanghongwei** [comment]
@sonichy 你好，浅色模式下，背景黑色我认为还是看的清时间的呀，你那边是怎么出现的呢？
![image](https://user-images.githubusercontent.com/33614878/119497402-1d0c7880-bd97-11eb-8da8-fb847840fbbc.png)

**Comment by sonichy** [comment]
@0yanghongwei 透明度0

**Comment by 0yanghongwei** [comment]
@sonichy 你好，该需求目前还没有加入到开发计划中。

**Comment by smartsmallking** [comment]
Duplicate of #281
