### ISSUE TITLE
通知不需要保存

### ISSUE THREAD

**Issue by sonichy** [linuxdeepin/dde-dock#376]
通知只对单次启动有效，不需要保存到数据库，不然想看的找不到。
例如我写了个Bing壁纸切换shell，通知发送了壁纸的描述，通知里显示的却是几天前的。
![alt](https://ae01.alicdn.com/kf/Ubc997130bb244fb3b3231998ac2620dew.jpg)

**Comment by smartsmallking** [comment]
我印象中com.deepin.dde.Notifications服务有一个Close(可能是CloseNotification)的接口，当调用Notify接口发出通知后，调用此接口，通知会被关掉，并不会记录在通知中心的界面上
