### ISSUE TITLE
systray sometimes not showing up for pamac-tray

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/dde-dock#38]
As mentioned [here](https://github.com/linuxdeepin/developer-center/issues/250) sometimes the systray doesn't show up for me although **pamac-tray** has been launched. Other times it works fine.
I can't see an obvious difference in logs between session where the tray does show up and sessions where it launches normally.
In any case, here are the logs of a session without a tray. ``pidof pamac-tray`` shows that it is actually running. When I launch skype for example, the tray shows up but without a pamac icon.
[dde-dock_log.txt](https://github.com/linuxdeepin/dde-dock/files/923269/dde-dock_log.txt)
[dde-desktop_log.txt](https://github.com/linuxdeepin/dde-dock/files/923268/dde-desktop_log.txt)

**Comment by oberon2007** [comment]
anyone?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
