### ISSUE TITLE
Can't open a file dragging into dock with Smart Hide mode

### ISSUE THREAD

**Issue by zbandhan** [linuxdeepin/dde-dock#380]
Suppose I have several applications opened in the dock and I'd like to open a file from file manager by dragging into dock with an application opened there that's not possible now if Smart Hide mode is on. Because the dock can't be visible with mouse button clicked in the Smart hide mode.

Regard

**Comment by 0yanghongwei** [comment]
In the Smart Hide mode, when the currently activated window blocks the dock, the dock is hidden. At this point, the dock is not displayed when the left mouse button is pressed.We do not support this operation.

**Comment by zbandhan** [comment]
@0yanghongwei Sometimes it feels very important. Do you have any plan to support it in the future?

**Comment by 0yanghongwei** [comment]
@zbandhan Maybe there will be in the future, but there is no plan yet.

**Comment by smartsmallking** [comment]
When the taskbar is in smart hide mode and we are in a full-screen scrolling page, the taskbar should be hidden. At this time, we use the mouse to hold down the scroll bar on the page. When we move to the taskbar, the taskbar will be triggered. The experience is not friendly, so we limit the taskbar from hidden to displayed when the mouse is held down.
@zbandhan
