### ISSUE TITLE
Wifi icon problems and other

### ISSUE THREAD

**Issue by alexk136** [linuxdeepin/dde-dock#383]
My laptop:
IBM thinkpad e470 i5 Deeepin 20 (+ update 25.11.2020)

1. Wifi Icon dont show signal (Update should fix it but it not)
2. Sometimes doc wifi pop dont show networks.. so you have to go to Settings menu to chiise network
3. Wifi connected but no internet provided (probably its wifi modem drivers problem i have Atheros QCA9377 802.11ac).
4. Sound icons always grey (dark grey) and dont show any volume info.
5. And still apperars delay on any doc action after system working 1-2 hours. After clicking icon in doc app opens after 5-10 sec, same animation, same main menu or any trey icon.

**Comment by 0yanghongwei** [comment]
@alexk136 Hello, do you still have this problem? If it exists, can you provide me with a screenshot or gif?

**Comment by alexk136** [comment]
> @alexk136 Hello, do you still have this problem? If it exists, can you provide me with a screenshot or gif?

Hi! thank you for your replay! After new update (27/05/21) all fine! Thank you! I have new issue with language selection (it's not working at all))

**Comment by 0yanghongwei** [comment]
> > @alexk136 Hello, do you still have this problem? If it exists, can you provide me with a screenshot or gif?
> 
> Hi! thank you for your replay! After new update (27/05/21) all fine, from list! Thank you! I have new issue with language selection (it's not working at all))

Can you describe it in detail?

**Comment by alexk136** [comment]
> Can you describe it in detail?

All this after lasdt update.

1. language icon dissapear (for me, i have RU and ENG lang)
2. keyboard switching not working (after restart, sometimes work for 1-2 min)
3. i tried: _dpkg-reconfigure keyboard-configuration_  not helps
4. also, language plugin not appears in dde-doc popup menu.

If you need more information, let me know.. i will try to provide as much info as you need! Thank you!

**Comment by 0yanghongwei** [comment]
@alexk136 Hello, you can open a new issue for new issues, thank you.

**Comment by smartsmallking** [comment]
@alexk136 

commit a84c837ba1299d3c35163d0f1f179e1a9df5d677

According to the latest design, the task bar no longer displays the keyboard layout icon, and the latest version of the control center provides keyboard layout management. If you are a developer, you can roll back this submission and compile it yourself 
-_-
