### ISSUE TITLE
Dde dock clock bug

### ISSUE THREAD

**Issue by microbite1** [linuxdeepin/dde-dock#384]
@hualet @xmuli Dde-dock clock not changing to 2 digit automatically  when 9:59 am or 9:59 pm to 10:00am or 10:00 pm. After change time there is only time 0.00 am or pm. After clicking time dde refreshes time to 2 digit.

**Comment by 0yanghongwei** [comment]
@microbite1  Hello, I have been fixed in the latest source code.

**Comment by aksharlabs** [comment]
> @microbite1 Hello, I have been fixed in the latest source code.

Ok aspecting to get latest release via update

**Comment by 0yanghongwei** [comment]
5784fa375395d45c7a86a210c4fe8d79d2a0d131
It has been fixed!
