### ISSUE TITLE
大量 electron 软件在任务栏同时出现gtk和qt两个托盘图标

### ISSUE THREAD

**Issue by Hibanaw** [linuxdeepin/dde-dock#398]
如
listen1/listen1_desktop#324
Clansty/Icalingua#68
论坛反馈 QQ 音乐、electron SSR 等也有类似问题

**Comment by CoelacanthusHex** [comment]
Duplicate with https://github.com/linuxdeepin/dde-dock/issues/142 ?

**Comment by ClayStan** [comment]
已确定是 dde 后端问题，正在解决中

**Comment by andot** [comment]
![image](https://github.com/linuxdeepin/dde-dock/assets/232161/4eaf961f-c5b2-4a92-9840-63a84f004792)
这个问题并没有修复，2024年，deepin v23 beta3 仍然存在该问题。
