### ISSUE TITLE
items right click problem

### ISSUE THREAD

**Issue by MetaiR** [linuxdeepin/dde-dock#40]
if a maximized app (like chrome browser) is opened and click right on dock item, the item navigation menu (which has "close all window" option in it) won't appear. it goes behind the app.
this image will show what I said.

![deepinscreenshot20170426133424](https://cloud.githubusercontent.com/assets/7807264/25426651/149255a2-2a85-11e7-977d-779b40bad602.png)

**Comment by MetaiR** [comment]
it fixed on : 2017-04-27

**Comment by tetration** [comment]
If you click on the middle button, on the top right between the minimize and exit button, it will stretch the chrome windows to fit the entire screen. Afterwards you will be able to click on the close all window, since the chrome window(or any other app window) wont make it go behind it.

**Comment by MetaiR** [comment]
it's not the chrome. the problem is for all applications
in the picture the, it wasn't in maximize mode to show my point.
if the application is maximized the item right click panel is hide behind the application window.
no one has this problem?

**Comment by MetaiR** [comment]
One of my friends installed manjaro with deepin de on real machine and we realised it has this problem too

**Comment by sbwtw** [comment]
That's a bug for deepin-menu, and I think it's already fixed at git. @hualet

**Comment by MetaiR** [comment]
I saw deepin-menu git history and I think it was solved. it's too bad that updates coming so late.

**Comment by SalahAdDin** [comment]
But it depends of your distribution's packages maintainer, isn't it?

**Comment by sbwtw** [comment]
@SalahAdDin yes, just please waitting for new version.

**Comment by MetaiR** [comment]
@SalahAdDin yep, but when I use deepin os I expect to have fewer bugs and more up to date than other disterbiutions that using deepin de

**Comment by MetaiR** [comment]
after about 1 year this but still there :cry:

**Comment by SalahAdDin** [comment]
@sbwtw

**Comment by es20490446e** [comment]
Same for me, see this [screen cast](https://youtu.be/ccDmPsFEjrA).

**Comment by MetaiR** [comment]
I'm reaching this result that this problem happens due to a problem in nvidia configuration.

if you have a laptop with a dual graphics card and using bumblebee, let me know @es20490446e @SalahAdDin 

if you have, follow this structure and see if it's going to be fixed or not (share the result)

run this command:
```sh
cat /proc/acpi/bbswitch
```

if you see `OFF` it should work well and if this problem remains just logout and login again

if you see `ON`

run:

```sh
lsmod | grep nvidia
```
it must have no result (if you config bumblebee right)

if it had, run this:
```sh
sudo modprobe -r nvidia
```
it should be done without any problem and return nothing but if it says something like `nvidia is busy` just kill your session by `ctrl+alt+backspace` and do this on other tty again

> **note:** do not use `-f` option to remove this module it may cause a hang on your session and if you want to restart it takes about 5-10 minutes and the problem will be remain

then run this:
```sh
sudo tee /proc/acpi/bbswitch <<<OFF
```
you can check 
```sh
cat /proc/acpi/bbswitch
```
to see if it takes effect or not

after these commands just login or if you already in kill session and relogin

if the problem still remains, make sure the result of `bbswitch` is `OFF` and relogin again.

let us know if this is works

**Comment by es20490446e** [comment]
No dual graphics here, Intel alone.

**Comment by SalahAdDin** [comment]
I have dual graphics with `bumblebee`.
@MetaiR 
I get this:
```
lsmod | grep nvidia                                         
nvidia              14045184  3
ipmi_msghandler        57344  2 nvidia,ipmi_devintf
sudo modprobe -r nvidia                                     
[sudo] password for salahaddin: 
modprobe: FATAL: Module nvidia is in use.
```

**Comment by es20490446e** [comment]
The display configuration is:
`xrandr --output LVDS-1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output DP-1 --off --output HDMI-1 --off --output VGA-1 --off`

**Comment by smartsmallking** [comment]
If the problem still exists, reopen it
