### ISSUE TITLE
dock 示例不能编译

### ISSUE THREAD

**Issue by outersky** [linuxdeepin/dde-dock#400]
该安装的都安装了，但是按照文档一步一步下来，  例子还是无法编译

```tony@tonybook:/data/work/deepin/dde-dock/plugins/plugin-guide/home_monitor$ mkdir build
tony@tonybook:/data/work/deepin/dde-dock/plugins/plugin-guide/home_monitor$ cd build
tony@tonybook:/data/work/deepin/dde-dock/plugins/plugin-guide/home_monitor/build$ cmake ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /bin/pkg-config (found version "0.29") 
-- Checking for module 'dde-dock'
--   Found dde-dock, version 1.0
-- Configuring done
-- Generating done
-- Build files have been written to: /data/work/deepin/dde-dock/plugins/plugin-guide/home_monitor/build
tony@tonybook:/data/work/deepin/dde-dock/plugins/plugin-guide/home_monitor/build$ make -j4
Scanning dependencies of target home_monitor_autogen
[ 12%] Automatic MOC for target home_monitor

AutoMoc subprocess error
------------------------
The moc process failed to compile
  "/data/work/deepin/dde-dock/plugins/plugin-guide/home_monitor/homemonitorplugin.h"
into
  "/data/work/deepin/dde-dock/plugins/plugin-guide/home_monitor/build/home_monitor_autogen/EWIEGA46WW/moc_homemonitorplugin.cpp".

Command
-------
/usr/lib/qt5/bin/moc -I/usr/include/libdtk-5.4.20/DCore -I/usr/include/libdtk-5.4.15/DGui -I/usr/include/libdtk-5.5.3/DWidget -I/usr/include/dde-dock -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB --include /data/work/deepin/dde-dock/plugins/plugin-guide/home_monitor/build/home_monitor_autogen/moc_predefs.h -o /data/work/deepin/dde-dock/plugins/plugin-guide/home_monitor/build/home_monitor_autogen/EWIEGA46WW/moc_homemonitorplugin.cpp /data/work/deepin/dde-dock/plugins/plugin-guide/home_monitor/homemonitorplugin.h

Output
------
/data/work/deepin/dde-dock/plugins/plugin-guide/home_monitor/homemonitorplugin.h:13: Error: Undefined interface

make[2]: *** [CMakeFiles/home_monitor_autogen.dir/build.make:58：CMakeFiles/home_monitor_autogen] 错误 1
make[1]: *** [CMakeFiles/Makefile2:110：CMakeFiles/home_monitor_autogen.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2
```

**Comment by smartsmallking** [comment]
![image](https://user-images.githubusercontent.com/19384974/148781393-8a5f6cc4-64e1-4de8-b098-52f0788aa96c.png)

**Comment by outersky** [comment]
@smartsmallking  请教一下你的moc 是什么版本？ 我的是 
Qt Meta Object Compiler version 67 (Qt 5.9.7)

**Comment by smartsmallking** [comment]
> @smartsmallking 请教一下你的moc 是什么版本？ 我的是 Qt Meta Object Compiler version 67 (Qt 5.9.7)

这个版本怎么看的，我的qt版本是5.11.3.40

**Comment by outersky** [comment]
> > @smartsmallking 请教一下你的moc 是什么版本？ 我的是 Qt Meta Object Compiler version 67 (Qt 5.9.7)
> 
> 这个moc版本怎么看的，我的qt版本是5.11.3.40

![image](https://user-images.githubusercontent.com/789988/148864602-e7ade266-866e-4ff1-a46c-bc32d9c49644.png)

**Comment by outersky** [comment]
我知道了，不是moc的问题，是include的问题，我生成的moc命令为：

`/usr/lib/qt5/bin/moc -I/usr/include/libdtk-5.4.26/DCore -I/usr/include/libdtk-5.4.23/DGui -I/usr/include/libdtk-5.5.3/DWidget -I/usr/include/dde-dock -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB --include /data/work/deepin/dde-dock/plugins/plugin-guide/home_monitor/build/home_monitor_autogen/moc_predefs.h -o /data/work/deepin/dde-dock/plugins/plugin-guide/home_monitor/build/home_monitor_autogen/EWIEGA46WW/moc_homemonitorplugin.cpp /data/work/deepin/dde-dock/plugins/plugin-guide/home_monitor/homemonitorplugin.h`

注意里面有一个 `-I/usr/include/dde-dock` ; 但是在 `homemonitorplugin.h`里面，导入的头文件里面写的是`#include <dde-dock/pluginsiteminterface.h>`  ；这两个地方都有dde-dock，我把 `homemonitorplugin.h` 里面的`dde-dock`去掉一个就好了。

**Comment by outersky** [comment]
@smartsmallking 麻烦你看看你机器上 `pkg-config --cflags --libs dde-dock`这个命令输出的是啥？

**Comment by outersky** [comment]
小白我是不是被误导了：
![image](https://user-images.githubusercontent.com/789988/148867179-bcf13693-02db-4ce9-a420-ac2fba9b3356.png)

日期插件里面的`#include`就是不带 dde-dock 的
