### ISSUE TITLE
Icons not updateing

### ISSUE THREAD

**Issue by ire4ever1190** [linuxdeepin/dde-dock#41]
When ever I changed the icons it won't change it on the dock

**Comment by sbwtw** [comment]
What's your dock version. and what's the way you switch icon.

**Comment by ire4ever1190** [comment]
4.2.1-1 
I switch icons using the deepin sidebar

**Comment by sbwtw** [comment]
What distrbution are you using, deepin or other else?
does other component worked? launcher or file manager.

**Comment by ire4ever1190** [comment]
Im using arch linux the launcher changes icons and file manger and other deepin programs work

**Comment by ire4ever1190** [comment]
It doesnt change when in effencient mode either

**Comment by SalahAdDin** [comment]
@sbwtw I have the same problem. And others.

**Comment by sbwtw** [comment]
I think this problems is already fixed.

**Comment by SalahAdDin** [comment]
@sbwtw Re open it, I still we have the same problem.
![aunproblemas](https://user-images.githubusercontent.com/5034215/32454699-aaceb4de-c328-11e7-8353-77b556b99aca.png)
