### ISSUE TITLE
Problem rendering icons

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/dde-dock#42]
I have the next problem:
![seleccion_003](https://cloud.githubusercontent.com/assets/5034215/26038682/75cf0190-3916-11e7-8f1f-1039102281cb.png)

First: some icons haven't his real icon in docker.
Second: Places status/indicator icon doesn't works fine.

My SO is Antergos Linux updated.

**Comment by ire4ever1190** [comment]
Im pretty sure this has to do with the fact that the dock uses deepin icon pack and it doesnt have all the icons

**Comment by sbwtw** [comment]
This bug is fixed with this https://github.com/linuxdeepin/dde-file-manager/commit/092314c11a9516c5014a6651b44ebaf353a15546 commit

**Comment by SalahAdDin** [comment]
We are waiting for new updates :D

**Comment by SalahAdDin** [comment]
@sbwtw I think i found the problem: `deepin-disk-mount-plugin` isn't installed in my OS because it isn't in `pacman`, by the way, in `ArchLinux` repositories:
![noestaelplugin](https://user-images.githubusercontent.com/5034215/32770178-b9cd54e2-c92f-11e7-8d49-8bb8150a0cce.png)

**Comment by zhtengw** [comment]
Hi José,
   dde-disk-mount-plugin is provided by deepin-file-manager.

Best Regards,
Aten Zhang

**Comment by SalahAdDin** [comment]
@zhtengw if it is provided by this package, why this icon doesn't works?

**Comment by SalahAdDin** [comment]
@zhtengw @sbwtw It is supossed that we have to get some like this:
![photo_2017-11-14_20-02-08](https://user-images.githubusercontent.com/5034215/32793369-ccb7bd9e-c976-11e7-8681-d80e0d836310.jpg)

Instead of this we have this:
![deepin-screen-recorder_select area_20171114200457](https://user-images.githubusercontent.com/5034215/32793512-2ad69288-c977-11e7-9af6-0475abd87711.gif)

Ok, it is working, but i have still a missin icon and the popup have different icons.
