### ISSUE TITLE
Add battery remaining percentage on "efficient" mode

### ISSUE THREAD

**Issue by peperunas** [linuxdeepin/dde-dock#47]
As the title says, it would be great to have the remaining percentage directly on the dock without having to hover on the battery icon.

**Comment by smartsmallking** [comment]
Now the battery icon can be displayed on the taskbar, there is no percentage, but you can see from the icon about how much power is left

**Comment by smartsmallking** [comment]
![Uploading image.png…]()

**Comment by smartsmallking** [comment]
![image](https://user-images.githubusercontent.com/19384974/115212776-73045580-a133-11eb-87c0-e6d1d001e5b6.png)
