### ISSUE TITLE
 Systems Crashes sometimes when right clicking on Deepin File Manager(in the DDE dock) and selecting New Window

### ISSUE THREAD

**Issue by tetration** [linuxdeepin/dde-dock#49]
My Systems Crashes sometimes when I right click in the **Deepin File Manager icon(inside the DDE dock)** and selecting the **New Window Option.** Nothing works afterwards. The System stops responding completely. 

However it looks like sometimes I can still access the NO-Gui Terminal Only option when the system crash occurs, by pressing at the same time CTRL+ALT+F1. However all my attempts in trying to save my freezed GUI session by using commands in the NO-GUI session are in vain, they never work. To sum it up I usually end up having to manually restart my system by pressing the shutdown button in my physical Desktop PC case, since my OS stopped responding completely.

OS version: Deepin 15.4 (However the same was happening in previous versions of Deepin)

**Comment by sbwtw** [comment]
@electricface ?

**Comment by tetration** [comment]
> @electricface ?

It happens exactly as I posted above. Its a really annoying issue. As a workaround, when I need multiple windows of the Deepin Folder Manager I get it by clicking in a folder in my dekstop. However it would be much more useful if I could open by  right clicking in the Deepin File Manager icon in the DDE_Dock and selecting New Window. But if I do that My system usuallys freezes...

**Comment by sbwtw** [comment]
That's maybe already fixed at latest versoin.

**Comment by DakshMiglani** [comment]
still hapenning.

**Comment by core01** [comment]
@sbwtw still happening in Deepin 15.7

**Comment by sbwtw** [comment]
@hualet

**Comment by hualet** [comment]
@listenerri

**Comment by listenerri** [comment]
@DakshMiglani @core01 @dwlsalmeida 
Everything works fine on my computer. Is there any way to stably reproduce this problem?

**Comment by core01** [comment]
@listenerri try to tap several times on DFM taskbar icon with right button

**Comment by listenerri** [comment]
> @listenerri try to tap several times on DFM taskbar icon with right button

Nothing happened...
Can you record a video about this problem?

**Comment by core01** [comment]
@listenerri I already moved to another distro , but for you here is the video, I had installed Deepin with latest updates available for today on VM. https://youtu.be/4OXuSzTz_7A

System freeze when I pin DFM to dock and right-click on it.

I'm very sorry about video quality and resolution I'm profession web developer, but noobie video maker)

**Comment by core01** [comment]
Hi all there is another video with better quality https://www.youtube.com/watch?v=kacsYbbxW6o

**Comment by core01** [comment]
@sbwtw @hualet @listenerri Did the video help?

**Comment by eulaussa** [comment]
> @listenerri I already moved to another distro , but for you here is the video, I had installed Deepin with latest updates available for today on VM. https://youtu.be/4OXuSzTz_7A
> 
> System freeze when I pin DFM to dock and right-click on it.
> 
> I'm very sorry about video quality and resolution (there is some offset) I'm profession web developer, but noobie video maker

I am having exactly the same problem on 15.7, the only way fixing it without restarting the computer is logging off and logging back in. Anybody has a solution?

**Comment by spykintl** [comment]
> > @listenerri I already moved to another distro , but for you here is the video, I had installed Deepin with latest updates available for today on VM. https://youtu.be/4OXuSzTz_7A
> > System freeze when I pin DFM to dock and right-click on it.
> > I'm very sorry about video quality and resolution (there is some offset) I'm profession web developer, but noobie video maker
> 
> I am having exactly the same problem on 15.7, the only way fixing it without restarting the computer is logging off and logging back in. Anybody has a solution?

Here is the solution,,But first we need to know the problem...The problem happens mostly in default deepin apps moreso when right clicking for options in the dock,well it so happens if you right click more than once the deepin window manager crushes...To solve this sacrifice animations for stability by disabling window effect in personi

> > @listenerri I already moved to another distro , but for you here is the video, I had installed Deepin with latest updates available for today on VM. https://youtu.be/4OXuSzTz_7A
> > System freeze when I pin DFM to dock and right-click on it.
> > I'm very sorry about video quality and resolution (there is some offset) I'm profession web developer, but noobie video maker
> 
> I am having exactly the same problem on 15.7, the only way fixing it without restarting the computer is logging off and logging back in. Anybody has a solution?

Here is the solution,,but first we got to know the problem..The problem is caused by deepin window manager crushing mostly after more than one right click in the taskbar moreso if you right click simultaneously...TO FIX THIS,,sacrifice animations for stability by turning off window effect in personalization settings...it will use metacity as the window manager now...if you are facing the problem in the moment,,just press ctrl+alt+t ,,it will open a terminal window and here type 
deepin-wm -r (will restart the window mngr) or killall deepin-wm (will kill window manager and use metacity) Sorry to y'all hope i helped...
