### ISSUE TITLE
Highlighted item on dock's task bar has a significant delay when switching windows

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-dock#5]
<a href="https://github.com/felixonmars"><img src="https://avatars.githubusercontent.com/u/1006477?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @felixonmars**
_Saturday Dec 12, 2015 at 16:40 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/178_

---

The current active window (group) is shown as highlighted on the dock's task bar. However, when switching windows, it often takes more than 1 second for the new (now active) item to be shown as highlighted and the old one reverted to normal.

**Comment by sbwtw** [comment]
fixed at latest version
