### ISSUE TITLE
Dock keeps popping up while in fullscreen games

### ISSUE THREAD

**Issue by PCPete68** [linuxdeepin/dde-dock#516]
Deepin Dock keeps popping up while in fullscreen games
Apologies if this is not the correct place to post issues, if it is please direct me to the correct spot to do so.
deepin-dock 5.5.9.1-3
kwin 5.25.3-1
Arch

This issue was closed ages ago and was mentioned that upgrading dock would fix it. As you can see mine is a lot more upto date than previous reported  but I am still suffeing from the popping up of the dock.

_Originally posted by @PCPete68 in https://github.com/linuxdeepin/dde-dock/issues/306#issuecomment-1192111772_

**Comment by BLumia** [comment]
Hi, sorry for the late response since we do not look into issue that were reported outside the developer-center repo. Could you report to [developer-center](https://github.com/linuxdeepin/developer-center/issues/new/choose) so we can look into it? Thanks!
