### ISSUE TITLE
Analog clock displays wrong time period (AM/PM)

### ISSUE THREAD

**Issue by TheMarketAnarchist** [linuxdeepin/dde-dock#52]
![clockwrongperiod](https://user-images.githubusercontent.com/30905416/29180668-7971e3f4-7dc6-11e7-84fa-49bb3c1f8e5c.png)

The time is correctly identified as 12:19 PM from the "hover text" but the icon displays 12:19 AM when set to 12-hour format.

I am running the Deepin Desktop Environment on Arch Linux.

**Comment by TheMarketAnarchist** [comment]
It seems to have corrected itself as the time now reads 3:01 PM. My computer was suspended and displayed the correct time after being woken up.

**Comment by sbwtw** [comment]
That's fixed at latest version.

**Comment by SiamSami** [comment]
It used to show PM during 12:xx AM and AM during 12:xx PM. However, this problem has been fixed in the latest version (fixed by me)
