### ISSUE TITLE
Problem with zenity

### ISSUE THREAD

**Issue by bigbruno** [linuxdeepin/dde-dock#53]
I found one problem with dde-dock, this don't show zenity, like:

zenity --info "testing"

Zenity don't appear in dde-dock

**Comment by bigbruno** [comment]
The problem also occurs with xfce4-screenshooter and with mate-color-select

**Comment by bigbruno** [comment]
Another problem, using thunar file renamer, not show in dock.

**Comment by smartsmallking** [comment]
![image](https://user-images.githubusercontent.com/19384974/115214666-55d08680-a135-11eb-8b91-633b5af30ff2.png)
![image](https://user-images.githubusercontent.com/19384974/115214911-8e706000-a135-11eb-915a-42d617524512.png)

It works fine now.
