### ISSUE TITLE
Transparent Dock

### ISSUE THREAD

**Issue by icp1994** [linuxdeepin/dde-dock#58]
Is there a way to make the background of the dock fully transparent instead of the grey-ish color it has currently?
![deepinscreenshot_desktop_20171017205439](https://user-images.githubusercontent.com/15713555/31673712-93b4dfae-b37d-11e7-8e54-11fc48146a7b.png)

**Comment by aiamuzz** [comment]
yes ... a way to control dock transparency would be good ... filed as bug ... does that mean there is an option to make the dock transparent ?

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
