### ISSUE TITLE
Dock panel could not be resized manually

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-dock#6]
<a href="https://github.com/fasheng"><img src="https://avatars.githubusercontent.com/u/3049011?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @fasheng**
_Tuesday Dec 29, 2015 at 04:10 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/206_

----

>The panel is not so flexible as it should be.
The height can't be changed, takes too much real estate.
Also the position can't be changed.

**Comment by manateelazycat** [comment]
New version dock along with deepin 15.3 will make user customize size of panel.

Thanks for your suggestion!
