### ISSUE TITLE
Smart Hide mode shaking.

### ISSUE THREAD

**Issue by kemalturk** [linuxdeepin/dde-dock#61]
While dock is slide up, it is shaking.I don't know maybe it's just relevant with my computer.

**Comment by aadhilkh2010** [comment]
I face the same issue. I also notice that the blur effect is delayed for a little while and initially appears as 100% transparent.

**Comment by n-osennij** [comment]
I have the same issue
gif  - https://vk.com/doc32555592_459857834

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
