### ISSUE TITLE
The dock to be clean

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/dde-dock#62]
Currently the status and plugins icons are placed in the dock, which makes it full of icons.

I think that ideally an interface should only show what's needed in the very moment, or constantly, and hide everything else. So [changeovers](https://www.leanproduction.com/smed.html) are as fast as possible.

Since status and plugin icons are only used punctually, I suspect they would be better placed somewhere inside the launcher. And the launcher icon differentiated from the rest of icons.

Thanks for your attention ;)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
