### ISSUE TITLE
Missing deepin disk mount plugin

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/dde-dock#63]
@sbwtw I think i found the problem that cause this bug https://github.com/linuxdeepin/dde-dock/issues/42: `deepin-disk-mount-plugin` isn't installed in my OS because it isn't in `pacman`, by the way, in `ArchLinux` repositories:
![noestaelplugin](https://user-images.githubusercontent.com/5034215/32770178-b9cd54e2-c92f-11e7-8d49-8bb8150a0cce.png)

**Comment by felixonmars** [comment]
The plugin should be in the deepin-file-manager package.

**Comment by SalahAdDin** [comment]
Yes, i think so, so, the icon problem, why is still here?

**Comment by SalahAdDin** [comment]
@felixonmars The problem is with the icon.

**Comment by felixonmars** [comment]
What problem? The icon works fine here.

**Comment by SalahAdDin** [comment]
Not in other operative systems, for exemplo Arch, @felixonmars

**Comment by felixonmars** [comment]
I am using Arch. Is there an empty icon that you can click and use the pop-out menu, or the plugin is simply missing?

**Comment by SalahAdDin** [comment]
Empty icon @felixonmars

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
