### ISSUE TITLE
Dock is showing over other windows when placed at the top when status is "Keep showing"

### ISSUE THREAD

**Issue by steve-todorov** [linuxdeepin/dde-dock#64]
Since last release 4.5.0 and 4.5.1, the dock is showing over other windows. See the screenshot.

![deepinscreenshot_google-chrome_20171118180146](https://user-images.githubusercontent.com/2303663/32982273-9461fd6c-cc8a-11e7-8f84-bbefe44cdd8d.png)

The dock works fine if places at the bottom or left. If placed at the top or right - the effect is the same as in the screenshot.

**Comment by skilian** [comment]
Same here, efficient mode works on left and right, not on top or bottom. In Fassion mode it works fine

**Comment by skilian** [comment]
i have compiled the dock under arch linux and replaced the version 4.5.5-2 with the compiled and it works fine again

**Comment by skilian** [comment]
i have checkout tag 4.5.6 and it works fine :)

**Comment by steve-todorov** [comment]
I confirm, issue has been resolved in 4.5.6. Thanks for the fix! :)
