### ISSUE TITLE
Deepin Dock ... missing/unstable/inconsistent ... !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/dde-dock#65]
The dock is behaving erratically ...

the last set of commands i had executed was while probing an issue found [here](https://github.com/linuxdeepin/dde-control-center/issues/75) ...

`gsettings set com.deepin.dde.daemon power false
`
`killall dde-session-dae;/usr/lib/deepin-daemon/dde-session-daemon
`

the above commands triggered an unstable control-center behavior as reported on the issue thread there ... i restarted and ended up with this issue ... [BootProblem](https://bbs.deepin.org/forum.php?mod=redirect&goto=findpost&ptid=148028&pid=403032&fromuid=94065)

out of luck(just like in the past) i was able to boot into OS and now i have this 'Dock inconsistency' ...

Dock is missing ... shows up accidentally sometimes ... but not responsive !!!

I am stuck ... if i reboot ... I run the danger of running into the 'BootProblem' ...

wow ... the Dock popped up just now ... while typing this issue ... it vanished after about 10 secs ...

hmmmmm ... what's happening !!!

**Comment by aiamuzz** [comment]
If it helps ... `/home/muz/.cache/deepin/dde-dock/dde-dock.log`

[dde-dock.log](https://github.com/linuxdeepin/dde-dock/files/1487852/dde-dock.log)

**Comment by aiamuzz** [comment]
i believe everytime the dock is visible briefly for a few seconds and i try to check if its working ... the following entry populates in the log file ...

```
2017-11-20, 19:34:09.888 [Debug  ] [docksettings.cpp     DockSettings::resetFrontendGeometry 425] void DockSettings::resetFrontendGeometry() QRect(260,723 845x45)
2017-11-20, 20:03:25.363 [Debug  ] [docksettings.cpp     DockSettings::resetFrontendGeometry 425] void DockSettings::resetFrontendGeometry() QRect(236,723 894x45)
2017-11-20, 20:03:36.630 [Debug  ] [docksettings.cpp     DockSettings::resetFrontendGeometry 425] void DockSettings::resetFrontendGeometry() QRect(260,723 845x45)
2017-11-20, 20:20:26.231 [Warning] [                                                         0] requestActivate() called for  QWidgetWindow(0x564032351510, name="Dtk::Widget::DArrowRectangleClassWindow")  which has Qt::WindowDoesNotAcceptFocus set.
```

if this helps ...

**Comment by aiamuzz** [comment]
Hi,

the following issue is breaking the dock and the system BIG TIME ... 

['Fast Screen Off' suspending the machine instead of suspending only the monitor](https://github.com/linuxdeepin/dde-control-center/issues/75)

let me know if you want to recreate this issue and dig out data(output logs) for you to trouble shoot.

```
gsettings set com.deepin.dde.daemon power false
killall dde-session-dae;/usr/lib/deepin-daemon/dde-session-daemon
```
the above commands mess the dock and system ... its a broken feeling ...

i have reversed it with the following commands ... and the system is back to its smooth experience.
```
gsettings set com.deepin.dde.daemon power true
killall dde-session-dae;/usr/lib/deepin-daemon/dde-session-daemon
```

However the 'fast screen off' suspending the whole machine issue persists ...

**Comment by aiamuzz** [comment]
I don't know guys ... i am encountering some crazy stuff ...

While test driving Deepin-Clone i had cloned my above unstable root partition(/dev/sda4) to another partition after booting into Deepin-Recovery ... i had ticked 'boot' option while cloning ... when i rebooted i was booted into the newly cloned partition(/dev/sda9) ... the Dock Issue existed in it too ... which is expected.

But today i booted into this cloned root partition (/dev/sda9) ... and with no explanation the dock is acting fine !!!

as reported yesterday the same state was highly unstable with the Dock acting nuts ... and today its working fine ... i can't explain that ...

This testing is proving to one hell of a roller-coaster ride !!!

But i am happy to do that ... as it will only result in highly stable Deepin OS ... hopefully !!!

**Comment by jouyouyun** [comment]
Very strange!

**Comment by aiamuzz** [comment]
do you want to probe deeper ?
do you want me to preserve the cloned partition ?

or shall we ignore and move on ?

**Comment by aiamuzz** [comment]
I wanted to report some observations/issues to newly installed Deepin-Recovery ... i cant find the official repository on github ... does it exist ? can you point me to the repository so that i can file an issue ?
