### ISSUE TITLE
strange behavior between audio and disk plugins on the dock ... BUG !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/dde-dock#67]
the audio plugin on the dock is acting as a disk plugin please find enclosed screenshots ...

mouse over bubble defines it as disk ...
![deepinscreenshot_select-area_20171127222332](https://user-images.githubusercontent.com/3283676/33278705-656c47c6-d3c2-11e7-96bf-2d52d9f64b15.png)

a click displays the disks instead of showing up audio control panel.
![deepinscreenshot_select-area_20171127222413](https://user-images.githubusercontent.com/3283676/33278711-6834b42a-d3c2-11e7-9c0e-e850bfad80a1.png)

**Comment by sbwtw** [comment]
what's your dde-dock version. That's an old bug and should be already fixed.

**Comment by aiamuzz** [comment]
dde-dock/panda,now 4.4.3-1 amd64 [installed]

**Comment by aiamuzz** [comment]
On Deepin 15.5 ... i guess the issue is no longer present ... closing
