### ISSUE TITLE
Menu behaviour on deepin dock

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/dde-dock#69]
Just upgraded to Deepin 15.5 ... test driving ... found a system tray anomaly ... posting a screen recorder snapshot ... the system tray does not hide/vanish after i click and move the cursor away on Deepin Music minimized tray icon ...

[Video Capture of the Issue](https://www.facebook.com/muzzammil.shariff/videos/10211361409015111/)

even certain menu's on the dock do not exit ... they are persistent ... overlapping applications ... can exit only on clicking on the dock bar.

![deepinscreenshot_20171203165453](https://user-images.githubusercontent.com/3283676/33524986-4417df48-d84c-11e7-88a1-3fee0bfe5049.png)

![deepinscreenshot_20171203165347](https://user-images.githubusercontent.com/3283676/33524987-474efdd6-d84c-11e7-8f14-9db1f0e47a62.png)

Anybody else facing the same ?

**Comment by aiamuzz** [comment]
seems the problem is more persistent than i thought the menu can be rid off ONLY when launching an app from the dock ... it stubbornly sits there until then.

![deepinscreenshot_20171204114625](https://user-images.githubusercontent.com/3283676/33538742-083c5f24-d8e9-11e7-97d0-68167f5c7150.png)

you can see in the snapshopt above that i have selected text on the web page and the dock is still sitting there stubbornly.

**Comment by flamedmg** [comment]
I can confirm the issue. Besides of that left click is not working for the context menu, that appears by rightclicking any of the dock elements. Menu does not hide itself, hides only if i press win key

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
