### ISSUE TITLE
Wrong behavior: overlapping, or some like it

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/dde-dock#71]
![deepin-screen-recorder_select area_20171221233527](https://user-images.githubusercontent.com/5034215/34278116-e84bf5e2-e6b9-11e7-8eae-744a3104c5b1.gif)

As you can see in the gift, after last actualization, in `Antergos Linux`, the dock have a strange behaviour:
it's a overlaping with the dock and a blurred dock, and i can't explain myself why it's happening.

It happens when the computer suspend the session(i close the tap) and i get into the session again, some time when i begins the session(turn on computer). It is only solved after close session and get into the session again.

What's happening?

**Comment by felixonmars** [comment]
It's a known issue under investigate by @sbwtw and @zccrs 

In the mean time please try to downgrade deepin-dock to 4.5.8-2.

**Comment by SalahAdDin** [comment]
@felixonmars @sbwtw @zccrs 
I tried to solve it unistalling and reinstallin this package, it didn't work.

But, curiously when i suspend my session(closing laptop's cover) and reopen it i get the new better dock:
![barradeensueno](https://user-images.githubusercontent.com/5034215/35121007-0574a2c0-fcab-11e7-8d32-44e2d3906070.png)
This is my dream dockbar: it solves this problem https://github.com/linuxdeepin/dde-dock/issues/63, and solve other problem that make impossible see the deepin seletec icons(only show gnome icons).

But still, it doesn't happen when i apply this "solution".

**Comment by SalahAdDin** [comment]
@zccrs @sbwtw What's up guy? What did you do? The beautiful dock has gone to hell! Now we have a stable bar, but ugly, with the same icon problem, both: no disk icon, not `marea` icons.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
