### ISSUE TITLE
The dock glitches on login if it's placed on the left side in efficient mode

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/dde-dock#72]
HOW TO REPRODUCE:
1. Right click on the dock, go to the menu "mode", and select "efficient mode".
2. Right click on the dock, go to the menu "location", and select "left".
3. Log out, and log in again.

RESULT:
The dock is glitched, wrongly placed on the screen.

SYSTEM INFO:
- Deepin Dock 4.5.9-1

**Comment by n-osennij** [comment]
I have the same problem!

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
