### ISSUE TITLE
Progress bar in the dock [IMPROVEMENT]

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/dde-dock#77]
Please make a progress bar in the dock. The progress bar should display the progress bar of an application. For example, the progress bar of downloading a program in google chrome.

You can use libunity to do so. I am not an expert but I think this documentation provided by canonical will help you guys out, https://wiki.ubuntu.com/Unity/LauncherAPI

Please enable this feature in the Deepin Dock.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
