### ISSUE TITLE
[Happening again with latest deepin-api] Right-clicking dock items causes freeze

### ISSUE THREAD

**Issue by Josephvb10** [linuxdeepin/dde-dock#78]
As mentioned on issue #428, right-clicking a dock icon causes the desktop environment to freeze.

This was supposedly fixed but it's happening again with deepin-api 3.1.20-1

**Comment by renanpallin** [comment]
Hi! Having the same issue around here and came to open an issue. Found your's and decide to give more information xD

I've inspect the logs, and I think this may be helpful:

`Jan 27 17:19:12 renanlinux com.deepin.dde.Dock[527]: 2018-01-27, 17:19:12.550 [Warning] [                                                         0] requestActivate() called for  QWidgetWindow(0x559b0e8f5540, name="Dtk::Widget::DArrowRectangleClassWindow")  which has Qt::WindowDoesNotAcceptFocus set.
Jan 27 17:19:12 renanlinux com.deepin.dde.Dock[527]: 2018-01-27, 17:19:12.616 [Debug  ] [mainwindow.cpp       MainWindow::expand                  561] expand
Jan 27 17:19:12 renanlinux com.deepin.dde.Dock[527]: 2018-01-27, 17:19:12.616 [Debug  ] [mainwindow.cpp       MainWindow::expand                  561] expand
Jan 27 17:19:41 renanlinux daemon/keybinding[670]: shortcut_manager.go:507: GrabKeyboard win 62914717 failed: GrabKeyboard Failed status: AlreadyGrabbed
Jan 27 17:19:47 renanlinux daemon/keybinding[670]: shortcut_manager.go:507: GrabKeyboard win 62914717 failed: GrabKeyboard Failed status: AlreadyGrabbed
Jan 27 17:20:04 renanlinux daemon/keybinding[670]: shortcut_manager.go:507: GrabKeyboard win 62914717 failed: GrabKeyboard Failed status: AlreadyGrabbed`

It's on pastebin too:
https://pastebin.com/RjjCbQmG

**Comment by Josephvb10** [comment]
Fixed with dtkwidget 2.0.6-2 and deepin-qt-dbus-factory 0.4.2-2.
