### ISSUE TITLE
Crashing on USB plug in 

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/dde-dock#79]
Every time I unplug and replug my mouse (because scroll direction is wrong sometimees), the dock crashes.

Using Arch.

**Comment by sbwtw** [comment]
Can you please upload the gdb backtrack info or coredump ?

**Comment by DasJott** [comment]
Please be so kind to provide a line for cli as I am not into gdb that much. Thank you!

**Comment by WeBredRaptors** [comment]
I'd also like to report this bug. Here's a coredump and bt of dde-dock.
[dde-dock-coredump-bt.txt](https://github.com/linuxdeepin/dde-dock/files/1801303/dde-dock-coredump-bt.txt)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
