### ISSUE TITLE
Move Deepin dock to top/bottom/left/right side

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/dde-dock#8]
<a href="https://github.com/sacatelasganasss"><img src="https://avatars.githubusercontent.com/u/12741783?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @sacatelasganasss**
_Thursday Jan 14, 2016 at 23:40 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/230_

----

deepin dock move???? deepin dock in top???

**Comment by manateelazycat** [comment]
This feature will implement in new version dock in deepin 15.3, please look forward it.

Thanks for your suggestion!
