### ISSUE TITLE
Problem in "Disks"

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/dde-dock#81]
If you click on the "Disks" option in the dock, then it shows wrong "progress" of space used of the partitions or disks on your computer. Here's the video of it....
![deepin-screen-recorder_select area_20180202210540](https://user-images.githubusercontent.com/33563064/35739778-efb3f4f0-085c-11e8-8c88-6970876fa62c.gif)

**Comment by BLumia** [comment]
This issue probably is fixed in current `dde-disk-mount-plugin`, if you still got this issue, feel free to fire a new bug report issue to developer-center :)
