### ISSUE TITLE
Icons order on Deepin-dock

### ISSUE THREAD

**Issue by boubouhkarim** [linuxdeepin/dde-dock#84]
The deepin dock doesn't remember the order of icons, once i reboot the order of icons is rolled back to default.
![deepinscreenshot_select-area_20180225215835](https://user-images.githubusercontent.com/5958072/36647002-0afd34b6-1a77-11e8-9aba-b1a2e7155593.png)

also worth mentioning that the mount plugin icon doesn't work with most of themes

**Comment by happyniko** [comment]
Yep, this issue still exists in the dock with Fashion Mode and also in Efficient Mode configuration with deepin OS itself. It's strange to have this issue in such a great Linux OS. I would be very glad, if I could customize the order of icons for my own needs.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
