### ISSUE TITLE
System Tray icons are not clickable

### ISSUE THREAD

**Issue by ilfarpro** [linuxdeepin/dde-dock#85]
After day of using Deepin 15.5 system tray icons become not working. But if I switch dock mode to Windows like it works. So for now my system tray doesn't work at all. 
Programs active in system tray: Telegram JetBrains, Toolbox, Keyboard Layout Switcher, MEGAsync, qBittorent

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
