### ISSUE TITLE
When a application is updated its icon if present in the dock will be removed

### ISSUE THREAD

**Issue by maofree** [linuxdeepin/dde-dock#87]
Hi
I use deepin on arch linux 64 bit
I've seen that the icons are removed from the dock if their applications are updated from pacman
each time I need to open these applications and lock their icons on the dock

can you fix it?

thanks
bye

**Comment by entwanderer** [comment]
+1

I noticed the same here, but it might not occur on all apps.

I specially experience this problem with firefox.

Very annoying.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
