### ISSUE TITLE
Smart hide - Auto show on new tray notification

### ISSUE THREAD

**Issue by FujiMakoto** [linuxdeepin/dde-dock#9]
When using smart hide, I believe it would make sense to have the dock automatically show with new taskbar notifications.

Otherwise, it's extremely easy to miss these when the taskbar is hidden, as you'll never notice them until the dock is triggered again elsewhere.

The dock can be quickly dismissed again by simply hovering over it again briefly as normal, and it would simply show again for any subsequent notifications after that.

**Comment by snyh** [comment]
Some tray icon may changed very frequency like fcitx .

**Comment by FujiMakoto** [comment]
Hm, very fair point. I'm not sure how feasible it would be to allow only specific applications in the icon tray to trigger the dock.

That or possibly a way to allow third party applications to interact with the dock, e.g.
```
dde-dock --show
dde-sock --hide
```
Then one could write plugin for things like Hexchat and handle message events that way. Though I'm sure sure how feasible that is either.

**Comment by snyh** [comment]
Of course there has ways to do this (dbus api) .

![image](https://cloud.githubusercontent.com/assets/1437166/13565962/2d6f72dc-e48e-11e5-92a6-8510c01cbaf7.png)
