### ISSUE TITLE
[improvement] Select screen for dock

### ISSUE THREAD

**Issue by ErikEklund** [linuxdeepin/dde-dock#90]
Right now the dock is always shown on the primary monitor. I would like have my primary monitor set to one screen (so that new application windows open up on that screen) but have my dock on another screen. It would be great if there was a right-click menu option to change what screen the dock appears on.

**Comment by orbatschow** [comment]
Maybe this doesn't belong directly to this issue, but it would be neat to have the option to display the dock on every display or on the displays of choice.

I can only speak for myself, but with multiple monitors, I'm losing the focus pretty easily when I have to look on another monitor just to do something on the bar.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
