### ISSUE TITLE
Got an error while compiling dde-dock 

### ISSUE THREAD

**Issue by purvalpatel** [linuxdeepin/dde-dock#92]
hello, 

i am compiling dde-dock package.
i have installed all dependency packages.
but during cmake process it will show below error at the end of cmake process.

` CMake Error at plugins/keyboard-layout/CMakeLists.txt:14 (find_package):
  By not providing "FindDFrameworkdbus.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "DFrameworkdbus", but CMake did not find one.

  Could not find a package configuration file provided by "DFrameworkdbus"
  with any of the following names:

    DFrameworkdbusConfig.cmake
    dframeworkdbus-config.cmake

  Add the installation prefix of "DFrameworkdbus" to CMAKE_PREFIX_PATH or set
  "DFrameworkdbus_DIR" to a directory containing one of the above files.  If
  "DFrameworkdbus" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/purval/dde-dock-master/build/CMakeFiles/CMakeOutput.log".

`
i have installed this below packages
`libdframeworkdbus libdframeworkdbus-dbgsym libdframeworkdbus-dev`

but still it will give the same error.

i have checked /usr/lib/x86_64-linux-gnu/cmake/ location
in here i did not found the files related to DFrameworkdbus which is responsible for cmake.

Any idea?

**Comment by aykutkaraca** [comment]
I got the same errors and I dont know why nobody answered for 2 years...

**Comment by 0yanghongwei** [comment]
Hello, generally you can get the dependencies through apt build-dep dde-dock. If you get incomplete, you can manually install the corresponding lib* and lib*-dev by reporting an error.
