### ISSUE TITLE
right clicking on items in dock displays menu behind all open windows

### ISSUE THREAD

**Issue by treeman1111** [linuxdeepin/dde-dock#93]
I'm using dde-dock 4.6.3.2-1 on Manjaro. When I right click on one of the dock icons to open the associated menu, the menu is hidden behind all windows on the desktop. It would be nice if the window were on top of every window instead. Here's an example of the behavior:
![deepinscreenshot_20180510090814](https://user-images.githubusercontent.com/5129580/39871068-b288dcf0-5431-11e8-8f3a-91b9ecb783d0.png)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
