### ISSUE TITLE
Adding a alternative for 'Keep Shown' option

### ISSUE THREAD

**Issue by EralpCelebi** [linuxdeepin/dde-dock#94]
This is not an issue just an enhancement idea that comes from my weird disturbance over the 'keep shown' option's disabling programs to cover all of the screen without going fullscreen. The spaces left really bother me and if the dock was always shown upon the programs that was below it, it would fix the Smart Hides weird rendering glitches.

**Comment by EralpCelebi** [comment]
![deepinscreenshot_select-area_20180521004431](https://user-images.githubusercontent.com/25103939/40284001-2b888b94-5c90-11e8-9474-32281f87d453.png)

As you can see, the Keep shown option leaves a big gap on the screen(Even tho it was made for visibility's sake, bothers people like me I suppose :p)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
