### ISSUE TITLE
RAM consumption problem after upgrade deepin to 15.6

### ISSUE THREAD

**Issue by brnathanlima** [linuxdeepin/dde-dock#97]
After I upgraded deepin to version 15.6 two days ago I'm facing a problem with dde-dock. Every time I start up the system and I interact somehow with the dock (passing the mouse over or clicking on some icon) the dock starts consuming available RAM and processor exponentially. I have to either suspend the dde-dock process or remove the package from the system to continue using the system.
![deepinscreenshot_20180618180618](https://user-images.githubusercontent.com/8891360/41562727-dae64b18-7323-11e8-8ba8-fd7ee79b1b31.png)

**Comment by bmansur** [comment]
I have the same problem.

**Comment by jouyouyun** [comment]
@sbwtw @kirigayakazushin

**Comment by kirigayakazushin** [comment]
I will try to reproduce and locate the problem.

**Comment by adrianopatrick** [comment]
I have one same problem
and more, used the fixed menu bar, without being the standard docker, the bar stopped working, sometimes it disappears.
![deepin screenshot_selecionar area_20180620105459](https://user-images.githubusercontent.com/358533/41662995-c64a7af2-7478-11e8-8b2c-8fb66c9b3751.png)

**Comment by adrianopatrick** [comment]
Hello everyone, I discovered that the behavior is something that happens in computers that have installed in Warsaw, which is a service that needs to be installed for applications to work in browsers. After uninstalling dde-dock it started working normally, without exaggeration of memory consumption and even my menu bar started to work too. I hope they will resolve this conflict, because Warsaw is widely used and necessary.

**Comment by brnathanlima** [comment]
Hi, Adriano. I tested a solution based on your discover and now the dde-dock works fine. Here is what I did: I used the command `sudo systemctl disable warsaw.service` to remove the service from the startup and I reinstalled the dde package which I removed on the day that I opened this issue. For my surprise the application that supposly requires the warsaw service still works even with the service inactive. Maybe you actually figured out the root cause of the problem. Thank you for your contribution and if something happen and the dde-dock stop working properly I post back here.

**Comment by adrianopatrick** [comment]
I believe the root cause is this. Ideally, the dde-dock team should check the reason for the incompatibility and the extent of the coexistence of the two services. @sbwtw @kirigayakazushin @jouyouyun

**Comment by brnathanlima** [comment]
I just updated deepin to version 15.7 and warsaw module to version 1.11.12-5 and the dock behaves normally.

**Comment by adrianopatrick** [comment]
I confirm that the problem has been resolved. Congratulations to all those involved.
