### ISSUE TITLE
Smart Hide not working as intended after upgrade to 15.6 !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/dde-dock#99]
Hi, 

I just discovered that the smart hide of the dock isn't working as should ... the dock is showing continuously overlapping the full screen applications.

Not entirely sure but could it be that [THIS](https://github.com/linuxdeepin/developer-center/issues/564) instance may have caused this issue ?

I think the first instance of the upgrade(before the unexpected downgrade and then re-upgrade now) not sure but i think smart hide was working fine !!!

Please let me know what i can try to get the dock to resume normal operation of the smart hide option.

PS : i have already tried `pkill dde-dock & dde-dock` ... didn't fix it, i am a little scared to restart with the fear of downgrading my system once again.

**Comment by aiamuzz** [comment]
I logged out and logged back in ... seems now the smart hide is working as expected ... 
I have however not restarted my machine in case you want to collect some logs ... if its important !

**Comment by jouyouyun** [comment]
@kirigayakazushin

**Comment by aiamuzz** [comment]
I restarted once after i reported this behavior ... and smart-hide worked fine until now !!!
its continuously showing, overlapping the full screen application.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
